/* Synthetic project illustrations. Every name, figure, and library record is invented for the walkthrough; nothing here is a task answer, a research finding, or an observed run. */
(function(scope){
  const C=typeof module!=='undefined'&&module.exports?require('./core.js'):scope.FinanceCore;
  const ACTIVITY='Liquidity and funding analysis (synthetic)';
  /* Synthetic stand-in for a saved failure-mode library pull: twelve records, ten eligible. Scores and usage figures are invented. */
  function library(){return {activity:ACTIVITY,count:12,pulledAt:'2026-10-07',modes:[
    {mode_id:'SYN-FM-01',name:'Facility release applied before its effective date',mechanism:'A later availability limit is applied to a funding date before the release condition has been met.',grader_detection_guidance:'Compare the eligibility limit used on the funding date with the limit the facility terms allow on that date.',category:'Period alignment',status:'approved',uses:14,avg_task_score:0.41,usage_share:0.07,overused:false},
    {mode_id:'SYN-FM-02',name:'Available credit counted as funded cash',mechanism:'Undrawn facility availability is added to usable cash as if it had been received.',grader_detection_guidance:'Check whether the cash bridge treats an undrawn commitment as a receipt; funded cash should include only settled draws and confirmed inflows.',category:'Cash recognition',status:'approved',uses:21,avg_task_score:0.38,usage_share:0.1,overused:true},
    {mode_id:'SYN-FM-03',name:'Covenant test run on the wrong period basis',mechanism:'A trailing covenant ratio is computed on a single quarter annualized instead of the defined trailing period.',grader_detection_guidance:'Recompute the ratio on the defined period and compare the headroom conclusion.',category:'Metric basis',status:'approved',uses:9,avg_task_score:0.52,usage_share:0.04,overused:false},
    {mode_id:'SYN-FM-04',name:'Restricted cash included in liquidity',mechanism:'Cash held in escrow or restricted accounts is counted as freely available liquidity.',grader_detection_guidance:'Trace the liquidity total to the restricted-cash disclosure and confirm the restricted balance was excluded.',category:'Entity perimeter',status:'approved',uses:17,avg_task_score:0.47,usage_share:0.08,overused:false},
    {mode_id:'SYN-FM-05',name:'Reimbursement notice treated as cleared cash',mechanism:'A reimbursement notice is counted as received cash before bank settlement, which the procedure makes the governing evidence.',grader_detection_guidance:'Check the settlement date behind any inflow counted on the funding date.',category:'Rule activation',status:'approved',uses:11,avg_task_score:0.44,usage_share:0.05,overused:false},
    {mode_id:'SYN-FM-06',name:'Intercompany balance netted against external payables',mechanism:'An intercompany payable is offset against third-party payments due, understating the external cash need.',grader_detection_guidance:'Compare payments due in the bridge with the external payables listing.',category:'Entity perimeter',status:'approved',uses:6,avg_task_score:0.55,usage_share:0.03,overused:false},
    {mode_id:'SYN-FM-07',name:'Unpaid borrowing treated as an inflow',mechanism:'Outstanding principal is added to cash because the facility exists.',grader_detection_guidance:'Reconcile borrowing movements to settled bank cash.',category:'Cash recognition',status:'approved',uses:12,avg_task_score:0.49,usage_share:0.06,overused:false},
    {mode_id:'SYN-FM-08',name:'Commitment fee omitted from the funding cost',mechanism:'The fee on the undrawn commitment is left out of the cost of the draw.',grader_detection_guidance:'Check the all-in cost against the fee clause in the facility terms.',category:'Completeness',status:'approved',uses:8,avg_task_score:0.58,usage_share:0.04,overused:false},
    {mode_id:'SYN-FM-09',name:'Business-day convention ignored for the release date',mechanism:'A release that falls on a weekend or holiday is treated as effective on the calendar date.',grader_detection_guidance:'Check the release date against the stated business-day calendar.',category:'Period alignment',status:'approved',uses:5,avg_task_score:0.6,usage_share:0.02,overused:false},
    {mode_id:'SYN-FM-10',name:'Draw request accepted above eligibility without comment',mechanism:'A requested borrowing above the eligible amount is passed through instead of capped or challenged.',grader_detection_guidance:'Compare the recommended draw with the eligible limit and look for an explicit challenge of the request.',category:'Judgment',status:'approved',uses:7,avg_task_score:0.62,usage_share:0.03,overused:false},
    {mode_id:'SYN-FM-11',name:'Draft mode awaiting approval',mechanism:'Not yet approved for use.',grader_detection_guidance:'None.',category:'Draft',status:'draft',uses:3,avg_task_score:0.3,usage_share:0.01,overused:false},
    {mode_id:'SYN-FM-12',name:'Approved but never used',mechanism:'No task has used this mode.',grader_detection_guidance:'None.',category:'Unused',status:'approved',uses:0,avg_task_score:0.2,usage_share:0,overused:false}
  ]};}
  function src(id,title,file,page,cell,excerpt,authority){return {...C.source(),id,title,file,page,cell,date:'2026-09-29',authority,version:'synthetic v1',excerpt,reviewStatus:'reviewed',suppliedToSolver:true};}
  function out(id,label,unit,correct,wrong,calculation,sourceIds,extra={}){return {...C.output(),id,label,unit,correct,wrong,calculation,sourceIds,...extra};}
  function mode(id,fields){return {...C.root(),id,causalGroup:id,reviewStatus:'reviewed',...fields};}
  function seed(kind){
    const p=C.blank();p.updatedAt='2026-10-07T00:00:00.000Z';
    if(kind==='cash'){
      p.title='Atlas reimbursement bridge (synthetic worked example)';p.task={id:'SYN-TASK-001',type:'Derivative task, workbook update',industry:'Corporate treasury (synthetic)',activity:ACTIVITY};p.versions={prompt:'syn-v1',workbook:'syn-v1',evaluator:'syn-v1'};
      p.business={objective:'liquidity for the planned payment',deliverable:'the cash bridge in the workbook',decision:'whether the payment can proceed',prompt:'Assess liquidity for the planned payment using the supplied materials. Update the cash bridge in the workbook and recommend whether the payment can proceed.'};
      p.notes='Synthetic worked example. Every figure, document, library record, and mode is invented to show a complete five-mode set; it is not a real task, a research finding, or an observed run.';
      const procedure=src('procedure','Treasury procedure: cash recognition','Treasury_Procedure.txt','Lines 2 to 3','','Only confirmed funded draws and confirmed inflows count as usable cash. Available credit is not cash received. Bank settlement evidence governs the funding date.','Treasury procedure governs cash recognition');
      const facts=src('facts','Cash facts','Cash_Facts.csv','','Rows 2 to 9','Opening usable cash 100; Confirmed funded draw 500 (settled 2026-09-30); Other confirmed inflows 50; Payments due 2026-10-01 1850; Reimbursement notice received 2026-09-30, settling 2026-10-02: 1300; Available facility 1800; Total facility 3000; Requested borrowing 2000.','Transaction records supplied to the solver');
      const facility=src('facility','Facility agreement: availability','Facility_Agreement.txt','Clause 4.2','','Availability is limited to 60% of the 3,000 commitment until the business day after reimbursement clearance. Draws above the available amount require lender consent.','Facility agreement governs availability');
      const bank=src('bank','Bank and facility statements','Statements.csv','','Rows 2 to 6','Bank statement 2026-09-30: incoming wire 500 (facility draw). Facility statement 2026-09-30: drawn 500, undrawn 2500.','Bank evidence governs settlement');
      p.sources=[procedure,facts,facility,bank];p.library=library();
      p.roots=[
        mode('fm-credit-as-cash',{title:'Available credit counted as funded cash',lane:'historical',modeId:'SYN-FM-02',mechanism:'metric_basis',sourceIds:['procedure','facts'],governingRule:'Only confirmed funded draws and confirmed inflows count as usable cash; available credit is not cash received (Treasury procedure, lines 2 to 3).',facts:'Funded cash on 2026-10-01 is 100 + 500 + 50 = 650. The facility shows 1,800 available but undrawn.',triggeringCondition:'The facility statement shows available credit next to the funded draw, and payments due exceed funded cash.',correctInterpretation:'Bridge = max(0, 1850 - 650) = 1,200; a draw of 1,200 is needed before the payment.',wrongInterpretation:'Add the 1,800 available facility to funded cash, so the bridge becomes 0 and the payment looks funded.',detectionMethod:'The bridge shows 0 and funded cash shows 2,450 or more; the 1,800 appears in the cash column without a settled draw behind it.',correctiveAction:'Count only settled draws and confirmed inflows; present availability as a funding option, not as cash.',expectedBehavior:'solve',classification:'strict-error',acceptableVariations:'Any bridge layout that reaches 1,200 from the same dated inputs; the draw can be shown as a separate line or netted, as long as availability is not counted as cash.',toleranceRationale:'Inputs are whole currency units, so the bridge is exact. No rounding policy applies.',headlineCorrect:'A 1,200 draw is required before the 1,850 payment can proceed.',headlineWrong:'The payment proceeds without a draw because the bridge reads 0.',outputs:[out('o-bridge','Cash bridge','currency units','1200','0','max(0, 1850 - 100 - 500 - 50) = 1200; wrong branch adds the 1800 availability to funded cash. Output cell: Bridge!C9.',['procedure','facts'],{threshold:'0',direction:'at-most'})]}),
        mode('fm-release-date',{title:'Facility release applied before its effective date',lane:'historical',modeId:'SYN-FM-01',mechanism:'period_alignment',sourceIds:['facility','facts'],governingRule:'Availability is 60% of the commitment until the business day after reimbursement clearance (Facility agreement, clause 4.2).',facts:'Reimbursement settles 2026-10-02, so full availability starts 2026-10-05 at the earliest. The requested borrowing of 2,000 is dated 2026-10-01.',triggeringCondition:'The requested borrowing is dated before the release boundary and exceeds the restricted availability.',correctInterpretation:'Eligibility on 2026-10-01 is 1,800; the 2,000 request exceeds it and needs lender consent or a reduction.',wrongInterpretation:'Treat the full 3,000 commitment as available on 2026-10-01 and approve the 2,000 request.',detectionMethod:'The liquidity schedule shows 3,000 of availability on 2026-10-01, or the 2,000 draw is approved without a consent note.',correctiveAction:'Apply the 60% limit until the business day after clearance; cap or challenge the request.',expectedBehavior:'solve',classification:'strict-error',acceptableVariations:'Either a capped 1,800 draw with a consent request or a 1,200 draw matching the bridge is acceptable; a 2,000 draw without comment is not.',toleranceRationale:'Facility limits are stated in whole units; exact comparison.',headlineCorrect:'Eligibility is 1,800; the 2,000 request cannot be approved as submitted.',headlineWrong:'The full 3,000 is available and the 2,000 request is approved.',outputs:[out('o-eligibility','Eligibility limit on the funding date','currency units','1800','3000','0.60 x 3000 = 1800 before the release boundary; wrong branch uses 3000. Output cell: Facility!D6.',['facility','facts'],{threshold:'2000',direction:'at-least'})]}),
        mode('fm-notice-as-cash',{title:'Reimbursement notice treated as cleared cash',lane:'historical',modeId:'SYN-FM-05',mechanism:'contract_conditions',sourceIds:['procedure','facts'],governingRule:'Bank settlement evidence governs the funding date (Treasury procedure, line 3).',facts:'A 1,300 reimbursement notice arrived 2026-09-30 but settles 2026-10-02, after the 2026-10-01 payment.',triggeringCondition:'A large notice is dated before the payment while its settlement date is after it.',correctInterpretation:'Funded cash on 2026-10-01 is 650; the notice is excluded until settlement.',wrongInterpretation:'Count the 1,300 notice as received cash, making funded cash 1,950 and the payment self-funded.',detectionMethod:'Funded cash shows 1,950 and no draw is recommended; the inflow line cites the notice date instead of the settlement date.',correctiveAction:'Use settlement dates for every inflow on the funding date.',expectedBehavior:'solve',classification:'strict-error',acceptableVariations:'Showing the notice as a dated future inflow is fine; counting it on 2026-10-01 is not.',toleranceRationale:'Whole currency units; exact.',headlineCorrect:'Funded cash is 650; a draw is still needed for the payment.',headlineWrong:'Funded cash is 1,950 and the payment needs no draw.',outputs:[out('o-funded','Funded cash on the funding date','currency units','650','1950','100 + 500 + 50 = 650; wrong branch adds the 1300 notice. Output cell: Bridge!C6.',['procedure','facts'],{threshold:'1850',direction:'at-least'})]}),
        mode('fm-draw-double-count',{title:'Settled draw counted from both statements',lane:'net-new',mechanism:'cross_document_bridge',sourceIds:['bank','facts'],governingRule:'The funded draw is one receipt evidenced twice: as a bank wire and as a facility drawdown (Statements, rows 2 to 3).',facts:'Bank statement shows incoming wire 500; facility statement shows drawn 500; both describe the same 2026-09-30 draw.',triggeringCondition:'The same draw appears in two supplied statements with different labels.',correctInterpretation:'Funded cash includes the draw once: 650.',wrongInterpretation:'Add the bank wire and the facility drawdown separately, so funded cash reads 1,150 and the bridge 700.',detectionMethod:'Funded cash shows 1,150 or the bridge shows 700; the reconciliation lists two draw lines for one settlement date.',correctiveAction:'Reconcile the bank and facility statements to one draw before building the bridge.',expectedBehavior:'reconcile',classification:'strict-error',duplicateCheck:'Differs from SYN-FM-02 (availability, not a settled draw), SYN-FM-07 (unpaid principal), and SYN-FM-05 (settlement timing). None of the ten shortlisted modes concerns the same receipt appearing in two statements.',acceptableVariations:'Any reconciliation that lands on one 500 draw; presentation of the two statements can vary.',toleranceRationale:'Whole currency units; exact.',headlineCorrect:'The bridge is 1,200 after reconciling the statements to one draw.',headlineWrong:'The bridge is 700 because the draw is counted twice.',outputs:[out('o-bridge-recon','Cash bridge after reconciliation','currency units','1200','700','1850 - 650 = 1200; wrong branch uses funded cash of 1150. Output cell: Bridge!C9.',['bank','facts'])]}),
        mode('fm-request-above-limit',{title:'Draw request above eligibility accepted without challenge',lane:'net-new',mechanism:'judgment_boundaries',sourceIds:['facility','facts'],governingRule:'Draws above the available amount require lender consent (Facility agreement, clause 4.2).',facts:'The request is 2,000; eligibility is 1,800; the bridge needs only 1,200.',triggeringCondition:'The requested borrowing exceeds both the eligible amount and the bridge.',correctInterpretation:'Recommend a 1,200 draw (or at most 1,800) and say explicitly that the 2,000 request cannot proceed without consent.',wrongInterpretation:'Pass the 2,000 request through as the recommended draw, or report 1,200 without saying the request was reduced.',detectionMethod:'The recommended draw is 2,000, or the memo never mentions that the request exceeded eligibility.',correctiveAction:'State the eligible limit, the needed amount, and the consent condition in the recommendation.',expectedBehavior:'push-back',classification:'judgment-call',duplicateCheck:'SYN-FM-10 covers accepting a request above eligibility; this mode differs because the eligibility figure itself is correct and the failure is silent reduction or silent pass-through, which SYN-FM-10 does not describe. It also differs from SYN-FM-01, where the eligibility date is misread.',acceptableVariations:'A 1,200 or 1,800 recommendation is acceptable when the excess request is called out; the exact wording of the challenge is open.',toleranceRationale:'Whole currency units; exact.',headlineCorrect:'Draw 1,200 and flag that the 2,000 request exceeds eligibility.',headlineWrong:'Draw 2,000 as requested.',outputs:[out('o-draw','Recommended draw','currency units','1200','2000','Needed draw = bridge 1200; eligible 1800; request 2000. Output cell: Recommendation!C4.',['facility','facts'],{threshold:'1800',direction:'at-most'})]})
      ];
      p.thesis='The five modes all sit on one dated bridge: counting availability or a notice as cash, misreading the release date, double counting a settled draw, and passing a request above eligibility. Each changes the recommended draw or the decision to pay, each is checkable from the supplied statements, and none is announced in the request.';
      p.guidance='The request is a cash bridge for a payment due on the first of the month, with a recommendation on whether the payment can proceed and how much to draw. The bridge figure and the recommended draw are the outputs that matter.\n\nWork from the treasury procedure for what counts as cash, the facts file for the dated balances, the facility agreement for availability, and the two statements for the settled draw. Where the facts file and the statements seem to disagree, the statements govern settlement.\n\nA tempting mistake is to add the undrawn availability to cash so the bridge reads zero. The correct bridge is funded cash of 650 against 1,850 due, which leaves 1,200 to draw. A related mistake is to count the reimbursement notice as received; it settles after the payment date, so it stays out.\n\nThe availability on the payment date is 1,800, not the full 3,000, because the release follows reimbursement clearance by a business day. A recommendation that draws the requested 2,000 without comment misses that limit; a good answer draws 1,200 or at most 1,800 and says the request exceeds eligibility.\n\nThe settled draw of 500 appears on both the bank statement and the facility statement. Counting it twice gives funded cash of 1,150 and a bridge of 700. Either a 1,200 or an 1,800 draw with the limit called out is fine; the layout of the bridge is open.';
      p.oracle={kind:'cash',inputs:{facility:'3000',fraction:'0.60',asOf:'2026-10-01',clearDate:'2026-10-02',releaseDate:'2026-10-05',opening:'100',fundedDraw:'500',otherInflows:'50',outflows:'1850',unit:'currency units'},result:null};
      p.gates={};
    } else if(kind==='lending') {
      p.title='Meridian securities lending (synthetic, partially built)';p.task={id:'SYN-TASK-002',type:'Derivative task, workbook update',industry:'Asset management (synthetic)',activity:'Securities lending and trade sizing (synthetic)'};
      p.business={objective:'the proposed share purchase and its cash requirements',deliverable:'the funding schedule in the workbook',decision:'the maximum feasible trade and whether the purchase can proceed',prompt:'Assess the proposed share purchase using the supplied trading and lending records. Update the funding schedule in the workbook and recommend the maximum feasible trade and whether the purchase can proceed.'};
      p.notes='Synthetic illustration showing a build in progress: one net-new mode recorded, no library imported, and the set still open. Figures are invented.';
      const terms=src('terms','Lending terms: record-date obligation','Lending_Terms.txt','Lines 2 to 3','','The dividend obligation is fixed by shares on loan at the record date. Returning shares after that date does not remove the obligation. Only remaining cash after obligations is available for the proposed share purchase.','Lending terms govern the obligation');
      const trade=src('trade','Trade facts','Trade_Facts.csv','','Rows 2 to 7','Cash budget 100000; Price per share 25; Shares on loan at record date 10000; Dividend per share 0.8; Proposed trade shares 3900; Shares returned after record date 6000.','Trading records supplied to the solver');
      p.sources=[terms,trade];
      p.roots=[mode('fm-record-date',{title:'Record-date dividend obligation omitted',lane:'net-new',mechanism:'period_alignment',sourceIds:['terms','trade'],governingRule:'The dividend obligation is fixed by shares on loan at the record date (Lending terms, line 2).',facts:'10,000 shares were on loan at the record date; 6,000 were returned later. The obligation is 10,000 x 0.8 = 8,000.',triggeringCondition:'Shares returned after the record date make the current loan balance smaller than the record-date balance.',correctInterpretation:'Reserve 8,000, leaving 92,000; capacity = floor(92000 / 25) = 3,680 shares, so the 3,900 proposal must be reduced.',wrongInterpretation:'Size the obligation from the post-return balance or omit it, giving 4,000 shares of capacity and approving the 3,900 proposal.',detectionMethod:'Capacity of 4,000 shares, or an obligation computed on 4,000 shares on loan instead of 10,000.',correctiveAction:'Use the record-date population for the obligation and reserve it before sizing the trade.',expectedBehavior:'solve',classification:'strict-error',acceptableVariations:'Any sizing that reserves the record-date obligation first; rounding the trade to a lot size is acceptable if disclosed.',toleranceRationale:'Whole shares are exact; cash figures are whole units.',headlineCorrect:'Maximum trade 3,680 shares; reduce the 3,900 proposal.',headlineWrong:'Maximum trade 4,000 shares; the 3,900 proposal proceeds.',outputs:[out('o-capacity','Maximum whole-share trade','shares','3680','4000','floor((100000 - 10000 x 0.8) / 25) = 3680; wrong branch floor(100000 / 25) = 4000. Output cell: Sizing!C8.',['terms','trade'],{threshold:'3900',direction:'at-least'})]})];
      p.roots[0].reviewStatus='pending';p.oracle={kind:'dividend',inputs:{budget:'100000',price:'25',loanShares:'10000',dividend:'0.8'},result:null};
    } else if(kind==='carveout') {
      p.title='Circular carve-out (synthetic, deliberately incomplete)';p.task={id:'SYN-TASK-003',type:'Derivative task, memo and workbook',industry:'Private capital (synthetic)',activity:'Transaction waterfall analysis (synthetic)'};p.versions={prompt:'syn-v2, confirm',workbook:'syn-v2, confirm',evaluator:'syn-v2, confirm'};
      p.business={objective:'the proposed transaction economics',deliverable:'the proceeds allocation and feasible offer in the workbook',decision:'an offer consistent with the governing rights',prompt:'Assess the proposed transaction economics using the supplied materials. Update the proceeds allocation and feasible offer in the workbook and recommend an offer consistent with the governing rights.'};
      p.notes='Synthetic illustration of an incomplete design: the operative equation, the wrong branch, and the source anchors are deliberately missing so the review findings show what a build still needs. Figures are invented placeholders.';
      const s={...C.source(),id:'placeholder',title:'Governing rights document, to be supplied',file:'Rights_Terms.docx',version:'synthetic v2, pending',authority:'Original source not yet inspected',date:'2026-10-07',excerpt:'Placeholder: the carve-out is a fixed share of proceeds net of itself; the operative clause has not been captured.'};
      p.sources=[s];
      p.roots=[mode('fm-carveout',{title:'Carve-out solved without the circular reference',lane:'net-new',mechanism:'contract_conditions',sourceIds:['placeholder'],governingRule:'Apply the current carve-out consistently within the proceeds equation and satisfy the joint constraints.',facts:'Placeholder reference output at 600 million of proceeds: carve-out 24.0 million; joint whole-cent ceiling 7.12 per share.',correctInterpretation:'Solve the simultaneous claim, then determine a price that satisfies all constraints at whole-cent precision.',wrongInterpretation:'Resolve the rights lookup but omit or incorrectly sequence the circular carve-out.',acceptableVariations:'Any mathematically equivalent, source-supported solution; accept alternative numerical methods within justified tolerances.',ambiguity:'Operative equation, source anchors, joint bounds, rounding policy, and the recomputed wrong branch are not supplied.',toleranceRationale:'Do not assume tolerance from displayed decimals. Derive it from the workbook precision and governing rounding policy.',headlineCorrect:'Joint whole-cent ceiling 7.12, subject to source verification.',headlineWrong:'Pending recomputation of the specific wrong branch.',outputs:[out('o-carve','Carve-out at 600 million','million','24.0','','Placeholder reference only; supply the operative equation before treating this as recomputed.',['placeholder']),out('o-ceiling','Joint whole-cent ceiling','per share','7.12','','Placeholder reference only; enter all derived bounds in the whole-cent helper.',['placeholder'])]})];
      p.roots[0].reviewStatus='pending';p.oracle={kind:'ceiling',inputs:{constraints:'',unit:'per share'},result:null};
    } else throw new Error('Unknown illustration.');
    return C.parseProject(p);
  }
  seed.library=library;seed.keys=['cash','lending','carveout'];
  if(typeof module!=='undefined'&&module.exports)module.exports=seed;else scope.FinanceExamples=seed;
})(typeof window!=='undefined'?window:globalThis);
