/* Offline extraction and deterministic package checks. No model, network, or workbook execution. */
(function(scope){
  'use strict';
  const ENGINE_VERSION='2.0.0';
  const LIMITS={fileBytes:50*1024*1024,totalBytes:100*1024*1024,entries:1500,documents:150,records:100000,nesting:3};
  const utf8=new TextDecoder('utf-8');
  const clean=s=>String(s??'').replace(/\u0000/g,'').trim();
  const fail=m=>{throw new Error(m);};
  function safePath(s){const p=String(s).replace(/\\/g,'/');if(p.startsWith('/')||p.split('/').includes('..')||/^[A-Za-z]:/.test(p))fail('Archive contains an unsafe path: '+p);return p;}
  const hex=bytes=>Array.from(bytes,b=>b.toString(16).padStart(2,'0')).join('');
  async function sha256(bytes){return hex(new Uint8Array(await globalThis.crypto.subtle.digest('SHA-256',bytes)));}
  let crcTable;
  function crc32(bytes){if(!crcTable){crcTable=Array.from({length:256},(_,n)=>{let c=n;for(let k=0;k<8;k++)c=c&1?0xedb88320^(c>>>1):c>>>1;return c>>>0;});}let c=0xffffffff;for(const b of bytes)c=crcTable[(c^b)&255]^(c>>>8);return(c^0xffffffff)>>>0;}
  async function readZip(input,budget={bytes:0}){
    const bytes=input instanceof Uint8Array?input:new Uint8Array(input);if(bytes.length>LIMITS.fileBytes)fail('Archive exceeds the 50 MB file limit.');const v=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength);let end=-1;
    for(let i=bytes.length-22;i>=Math.max(0,bytes.length-65557);i--)if(v.getUint32(i,true)===0x06054b50){end=i;break;}
    if(end<0)fail('Invalid ZIP: end record missing.');if(v.getUint16(end+4,true)||v.getUint16(end+6,true))fail('Multi-disk ZIP archives are not supported.');const count=v.getUint16(end+10,true),offset=v.getUint32(end+16,true);if(count===65535||offset===0xffffffff)fail('ZIP64 archives are not supported.');if(count>LIMITS.entries)fail('Too many archive entries.');
    const entries=new Map();let cursor=offset;
    for(let i=0;i<count;i++){
      if(cursor+46>bytes.length||v.getUint32(cursor,true)!==0x02014b50)fail('Invalid ZIP directory.');const flags=v.getUint16(cursor+8,true),method=v.getUint16(cursor+10,true),crc=v.getUint32(cursor+16,true),compressed=v.getUint32(cursor+20,true),size=v.getUint32(cursor+24,true),nlen=v.getUint16(cursor+28,true),extra=v.getUint16(cursor+30,true),comment=v.getUint16(cursor+32,true),local=v.getUint32(cursor+42,true);
      if(cursor+46+nlen+extra+comment>bytes.length)fail('Truncated ZIP directory.');const name=safePath(utf8.decode(bytes.subarray(cursor+46,cursor+46+nlen)));cursor+=46+nlen+extra+comment;
      if(name.endsWith('/'))continue;if(flags&1)fail('Encrypted archives cannot be read locally.');if(![0,8].includes(method))fail('Unsupported ZIP compression for '+name);if(entries.has(name))fail('Duplicate ZIP entry: '+name);if(size>LIMITS.fileBytes||budget.bytes+size>LIMITS.totalBytes)fail('Expanded package exceeds the 100 MB limit.');
      if(local+30>bytes.length||v.getUint32(local,true)!==0x04034b50)fail('Invalid ZIP local entry.');const start=local+30+v.getUint16(local+26,true)+v.getUint16(local+28,true);if(start+compressed>bytes.length)fail('Truncated ZIP entry.');
      entries.set(name,{name,size,crc,method,start,compressed});budget.bytes+=size;
    }
    async function get(name){const e=entries.get(name);if(!e)return null;const raw=bytes.subarray(e.start,e.start+e.compressed);let result;
      if(e.method===0)result=raw.slice();else{
        let stream;try{stream=new DecompressionStream('deflate-raw');}catch{fail('This browser does not support local ZIP decompression. Use a current browser or load plain text files.');}
        const reader=new Blob([raw]).stream().pipeThrough(stream).getReader(),parts=[];let length=0;
        for(;;){const {value,done}=await reader.read();if(done)break;length+=value.length;if(length>e.size||length>LIMITS.fileBytes){await reader.cancel();fail('ZIP expansion exceeded its declared size.');}parts.push(value);}
        result=new Uint8Array(length);let n=0;for(const part of parts){result.set(part,n);n+=part.length;}
      }
      if(result.length!==e.size||crc32(result)!==e.crc)fail('ZIP size or checksum mismatch: '+name);return result;
    }
    return {entries,get,text:async name=>{const b=await get(name);return b?utf8.decode(b):null;}};
  }
  function xml(text,name){if(!text)fail('Missing XML part: '+name);if(/<!DOCTYPE|<!ENTITY/i.test(text))fail('Unsupported XML entity declarations.');if(typeof DOMParser==='undefined')fail('XML extraction requires the browser parser. The analysis engine itself can run in Node.');const d=new DOMParser().parseFromString(text,'application/xml');if(d.getElementsByTagName('parsererror').length)fail('Malformed XML: '+name);return d;}
  const nodes=(el,name)=>Array.from(el.getElementsByTagNameNS('*',name));
  const textOf=el=>nodes(el,'t').map(x=>x.textContent).join('');
  const child=(el,name)=>Array.from(el.children).find(x=>x.localName===name);
  function partPath(base,target){if(target.startsWith('/'))return safePath(target.slice(1));const parts=base.split('/').slice(0,-1);for(const t of target.split('/')){if(t==='..')parts.pop();else if(t&&t!=='.')parts.push(t);}return safePath(parts.join('/'));}
  function inferRole(name){const n=name.toLowerCase();if(/(?:^|[\/_ -])(gaf|template)(?:[\/_. -]|$)/.test(n))return 'template';if(/(?:answer|golden|gold|grader|evaluator|rubric|reference.solution)/.test(n))return 'evaluator';if(/(?:prompt|instruction|task.request)/.test(n))return 'prompt';if(/(?:run|trajectory|batch|score|receipt)/.test(n))return 'run-evidence';if(/(?:review|audit|analysis|candidate)/.test(n))return 'audit';return 'source';}
  function record(locator,text,extra={}){return {locator,text:clean(text),...extra};}
  async function parseXlsx(bytes,name,budget){const z=await readZip(bytes,budget),book=xml(await z.text('xl/workbook.xml'),'workbook'),rels=xml(await z.text('xl/_rels/workbook.xml.rels'),'workbook relationships'),relMap={};nodes(rels,'Relationship').forEach(x=>{if(x.getAttribute('TargetMode')!=='External')relMap[x.getAttribute('Id')]=partPath('xl/workbook.xml',x.getAttribute('Target'));});
    const ss=await z.text('xl/sharedStrings.xml'),strings=ss?nodes(xml(ss,'shared strings'),'si').map(textOf):[];
    const records=[],sheets=[],definedNames=nodes(book,'definedName').map(x=>({name:x.getAttribute('name'),ref:x.textContent}));let formulas=0,missingCaches=0;
    for(const sh of nodes(book,'sheet')){
      const sheetName=sh.getAttribute('name'),rid=sh.getAttribute('r:id')||Array.from(sh.attributes).find(a=>a.localName==='id')?.value,part=relMap[rid];if(!part)fail('Missing worksheet relationship: '+sheetName);const d=xml(await z.text(part),part),cells=[];
      for(const c of nodes(d,'c')){const ref=c.getAttribute('r'),type=c.getAttribute('t')||'n',f=child(c,'f'),v=child(c,'v');let value=type==='inlineStr'?textOf(c):v?.textContent??'';if(type==='s')value=strings[Number(value)]??'';if(value===''&&!f)continue;
        const formula=f?.textContent??'',hasFormula=!!f;if(hasFormula){formulas++;if(!v||v.textContent==='')missingCaches++;}const r=record(sheetName+'!'+ref,hasFormula?'='+formula+' [cached: '+(value===''?'missing':value)+']':value,{sheet:sheetName,cell:ref,value,type,formula,hasFormula,formulaType:f?.getAttribute('t')||'',cachePresent:!!v&&v.textContent!=='',hidden:sh.getAttribute('state')==='hidden'||sh.getAttribute('state')==='veryHidden'});records.push(r);cells.push(r);if(records.length>LIMITS.records)fail('Workbook exceeds the 100,000 populated-cell limit.');
      }
      const byRow=new Map();for(const c of cells){const row=c.cell?.match(/\d+$/)?.[0];if(!byRow.has(row))byRow.set(row,[]);byRow.get(row).push(c);}for(const row of byRow.values()){const context=row.filter(c=>!c.hasFormula&&c.type!=='n').map(c=>c.value).filter(Boolean).slice(0,4).join(' · ');row.forEach(c=>c.context=context);}
      sheets.push({name:sheetName,state:sh.getAttribute('state')||'visible',populatedCells:cells.length});
    }
    const calc=nodes(book,'calcPr')[0];return {kind:'xlsx',records,metadata:{sheets,formulas,missingCaches,definedNames,externalLinks:[...z.entries.keys()].filter(x=>/^xl\/externalLinks\/externalLink\d+\.xml$/.test(x)).length,calculationSettings:calc?Object.fromEntries(Array.from(calc.attributes).map(a=>[a.name,a.value])):{},recalculated:false},warnings:['Formula values are saved workbook caches. This browser does not recalculate Excel formulas.']};
  }
  async function parseDocx(bytes,name,budget){const z=await readZip(bytes,budget),d=xml(await z.text('word/document.xml'),'document'),records=[];let p=0,table=0;const body=nodes(d,'body')[0];if(!body)fail('DOCX body is missing.');
    for(const element of body.children){if(element.localName==='p'){p++;const t=textOf(element);if(clean(t))records.push(record('Paragraph '+p,t));}else if(element.localName==='tbl'){table++;let row=0;for(const tr of Array.from(element.children).filter(x=>x.localName==='tr')){row++;let col=0;for(const tc of Array.from(tr.children).filter(x=>x.localName==='tc')){col++;records.push(record('Table '+table+', row '+row+', cell '+col,textOf(tc)));}}}}
    const headers=[...z.entries.keys()].filter(n=>/^word\/(header|footer)\d+\.xml$/.test(n));for(const n of headers){const t=textOf(xml(await z.text(n),n));if(clean(t))records.push(record(n,t));}
    return {kind:'docx',records,metadata:{paragraphs:p,tables:table},warnings:['DOCX locations use paragraph/table indices. Page numbers require a rendered document.']};
  }
  function parseCsv(text){const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++;}else quoted=!quoted;}else if(c===','&&!quoted){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);rows.push(row);row=[];cell='';}else cell+=c;}if(quoted)fail('CSV contains an unclosed quoted value.');if(cell||row.length){row.push(cell);rows.push(row);}return rows;}
  function parseText(bytes,name){const text=utf8.decode(bytes);if(text.includes('\u0000'))fail('Binary text encoding is not supported. Export UTF-8 text.');const ext=name.split('.').pop().toLowerCase();let records,metadata={};if(ext==='csv'){const rows=parseCsv(text);records=rows.map((row,i)=>record('Row '+(i+1),row.join(' | '),{values:row}));metadata.rows=rows.length;}else if(ext==='json'){const data=JSON.parse(text);metadata.jsonKind=data.kind||null;metadata.schemaVersion=data.schemaVersion||null;records=text.split(/\r?\n/).map((line,i)=>record('Line '+(i+1),line)).filter(r=>r.text);}else if(ext==='html'||ext==='htm'){const d=new DOMParser().parseFromString(text,'text/html');d.querySelectorAll('script,style').forEach(x=>x.remove());records=(d.body.textContent||'').split(/\n/).map((t,i)=>record('Text line '+(i+1),t)).filter(r=>r.text);}else records=text.split(/\r?\n/).map((line,i)=>record('Line '+(i+1),line)).filter(r=>r.text);
    if(records.length>LIMITS.records)fail('Text exceeds the record limit.');return {kind:ext,records,metadata,warnings:[]};
  }
  const textExtensions=new Set(['txt','md','csv','json','html','htm','log','py','js','xml','yaml','yml']);
  async function parseDocument(bytes,name,budget){const ext=name.split('.').pop().toLowerCase();if(ext==='xlsx'||ext==='xlsm')return parseXlsx(bytes,name,budget);if(ext==='docx')return parseDocx(bytes,name,budget);if(textExtensions.has(ext))return parseText(bytes,name);return {kind:ext||'unknown',records:[],metadata:{},warnings:[ext==='pdf'?'PDF extraction is not implemented. Add a text export for analysis.':'This file type is not parsed. It remains in the inventory.'],unsupported:true};}
  async function ingestFiles(files,{onProgress=()=>{}}={}){
    const documents=[],budget={bytes:0};let processed=0;const add=async(bytes,name,depth=0)=>{if(depth>LIMITS.nesting)fail('Nested archive limit exceeded.');if(bytes.length>LIMITS.fileBytes)fail(name+' exceeds the 50 MB file limit.');if(documents.length>=LIMITS.documents)fail('Package exceeds the 150-document limit.');onProgress({phase:'extracting',name,processed,total:files.length});
      if(/\.zip$/i.test(name)){const z=await readZip(bytes,budget);for(const e of z.entries.values()){if(e.name.startsWith('__MACOSX/')||e.name.endsWith('.DS_Store'))continue;await add(await z.get(e.name),name+' / '+e.name,depth+1);}return;}
      const hash=await sha256(bytes),doc={id:'file-'+hash.slice(0,16)+'-'+documents.length,name,bytes:bytes.length,sha256:hash,role:inferRole(name),roleBasis:'Filename heuristic; review the role if needed.',status:'extracted',kind:'',records:[],metadata:{},warnings:[]};
      try{Object.assign(doc,await parseDocument(bytes,name,budget));if(doc.unsupported)doc.status='unsupported';}catch(error){doc.status='error';doc.warnings=[error.message];}
      documents.push(doc);processed++;onProgress({phase:'extracted',name,processed,records:doc.records.length});await new Promise(resolve=>setTimeout(resolve,0));
    };
    for(const file of files)await add(new Uint8Array(await file.arrayBuffer()),safePath(file.webkitRelativePath||file.name));
    const fingerprint=await sha256(new TextEncoder().encode(documents.map(d=>d.name+'\0'+d.sha256).sort().join('\n')));return {schemaVersion:1,kind:'finance-task-package',id:'package-'+fingerprint.slice(0,16),title:files.length===1?files[0].name:'Imported task package',fingerprint,importedAt:new Date().toISOString(),documents,provenance:'Extracted locally from files selected by the user.',extractionVersion:ENGINE_VERSION};
  }
  function citation(doc,r){return {documentId:doc.id,file:doc.name,locator:r.locator,quote:r.text.slice(0,1200),sha256:doc.sha256};}
  function detectedFacts(pkg){const facts=[];for(const d of pkg.documents){if(!['source','template','proposal','prompt'].includes(d.role))continue;for(const r of d.records){if(r.hasFormula)continue;const text=[r.context,r.text].filter(Boolean).join(' ');if(!/\d/.test(text)||(!/(?:\$|%|million|shares?|options?|capital|proceeds|price|cap|sale|date|20\d\d|\d\.\d+\s*x\b)/i.test(text)&&d.kind!=='xlsx'))continue;facts.push({id:'fact-'+facts.length,text:text.slice(0,420),kind:d.kind==='xlsx'?'Extracted cell':'Extracted statement',citation:citation(d,r)});if(facts.length>=400)return facts;}}return facts;}
  function analyzePackage(pkg,{runId,now,durationMs=0}={}){
    validatePackage(pkg);const findings=[],proposals=[];let serial=0;const add=(severity,kind,title,summary,citations=[],suggestion='')=>{const id='finding-'+(++serial);findings.push({id,severity,kind,title,summary,citations});if(suggestion)proposals.push({id:'proposal-'+serial,findingId:id,title:suggestion,reason:summary,citations,status:'For review; no source file changed'});};
    const sourceDocs=pkg.documents.filter(d=>['source','template','proposal'].includes(d.role)),prompts=pkg.documents.filter(d=>d.role==='prompt');
    for(const d of pkg.documents){if(d.status==='error')add('error','structural','Could not extract '+d.name,d.warnings.join(' '),[],'Resolve the extraction error before relying on this package.');if(d.status==='unsupported')add('review','coverage','Unparsed file: '+d.name,d.warnings.join(' '),[],'Provide a supported text or Office version for analysis.');
      if(d.kind==='xlsx'){const errorCells=d.records.filter(r=>r.type==='e');if(errorCells.length)add('error','structural',errorCells.length+' saved formula error'+(errorCells.length>1?'s':'')+' in '+d.name,'These errors are present in the saved workbook. This pass did not recalculate it.',errorCells.slice(0,8).map(r=>citation(d,r)),'Inspect and recalculate the cited workbook cells.');const missing=d.records.filter(r=>r.hasFormula&&!r.cachePresent);if(missing.length)add('review','coverage',missing.length+' formulas have no saved value','Formula text was extracted, but these cells cannot be treated as recomputed numeric evidence.',missing.slice(0,6).map(r=>citation(d,r)),'Recalculate in a supported spreadsheet engine and retain the resulting artifact.');if(d.metadata.externalLinks)add('review','structural','Workbook depends on external links',d.name+' contains '+d.metadata.externalLinks+' external workbook link part(s). Availability and saved values need review.',[],'Include the linked source or document the fixed-value basis.');}
    }
    if(!prompts.length)add('review','coverage','No task prompt was identified','The filename-based inventory did not identify a solver prompt. Source extraction still completed.',[],'Add the actual prompt or set its role in the file inventory.');
    for(const d of prompts){const text=d.records.map(r=>r.text).join(' '),n=text.trim().split(/\s+/).filter(Boolean).length;if(n>40)add('review','structural','Business prompt contains '+n+' words','The authoring target is 40 words. Length alone does not establish answer leakage or difficulty.',d.records.slice(0,3).map(r=>citation(d,r)),'Shorten the business prompt while preserving the requested deliverable and necessary facts.');
      const teaching=d.records.filter(r=>/\b(?:round down|fixed.point|trap|gotcha|use the formula|subtract .*? from|include .*? in the denominator)\b/i.test(r.text));if(teaching.length)add('review','heuristic','Inspect potentially answer-bearing prompt wording','A wording rule matched the cited phrases. This is a review cue, not a verified financial defect. General directions to use supplied documents are allowed.',teaching.slice(0,4).map(r=>citation(d,r)),'Check whether the prompt gives away the governing interpretation.');}
    const hashes=new Map();for(const d of pkg.documents){const group=hashes.get(d.sha256)||[];group.push(d);hashes.set(d.sha256,group);}for(const group of hashes.values())if(group.length>1)add('info','structural','Duplicate file contents',group.map(d=>d.name).join('; ')+'. Identical bytes can be legitimate copies; no contradiction is inferred.');
    const versions=[...new Set(sourceDocs.flatMap(d=>[...d.name.matchAll(/(?:^|[_\s-])v(\d+)(?=[_.\s-]|$)/gi)].map(m=>'v'+m[1])))];if(versions.length>1)add('review','heuristic','Several filename version labels appear',versions.join(', ')+'. Filenames do not prove which terms govern. Historical records may be intentional; compare the authoritative package manifest before changing anything.',[],'Confirm source precedence against the actual receipt and content.');
    const hidden=sourceDocs.flatMap(d=>d.records.filter(r=>r.hidden).map(r=>({d,r})));if(hidden.length)add('review','coverage','Solver package includes hidden worksheet content',hidden.length+' populated cells are on hidden sheets. Inspect visibility and evaluator-only content; hidden does not mean wrong.',hidden.slice(0,4).map(({d,r})=>citation(d,r)),'Review hidden-sheet contents against the intended solver package.');
    const facts=detectedFacts(pkg);return {schemaVersion:1,kind:'deterministic-analysis-run',id:runId||'local-'+new Date().toISOString().replace(/[^0-9]/g,''),startedAt:now||new Date().toISOString(),completedAt:new Date().toISOString(),durationMs,engineVersion:ENGINE_VERSION,packageId:pkg.id,packageFingerprint:pkg.fingerprint,status:'completed',analysisType:'Deterministic local package checks',coverage:{files:pkg.documents.length,extracted:pkg.documents.filter(d=>d.status==='extracted').length,records:pkg.documents.reduce((n,d)=>n+d.records.length,0),formulas:pkg.documents.reduce((n,d)=>n+(d.metadata.formulas||0),0),facts: facts.length},findings,facts,proposals,limits:['No model was called. Keyword matches are review cues, not financial conclusions.','No arbitrary Excel formula recalculation, source-contradiction adjudication, or task-difficulty estimate was performed.','Historical source differences are not assumed to be errors. Correctness requires source precedence and business interpretation.']};
  }
  function validatePackage(p){
    if(!p||p.kind!=='finance-task-package'||p.schemaVersion!==1||!Array.isArray(p.documents)||p.documents.length>LIMITS.documents||typeof p.id!=='string'||typeof p.title!=='string'||!(/^[a-f0-9]{64}$/).test(p.fingerprint))fail('Unsupported package snapshot.');
    const ids=new Set();let count=0;for(const d of p.documents){if(!d||typeof d.id!=='string'||ids.has(d.id)||typeof d.name!=='string'||typeof d.kind!=='string'||!Number.isFinite(d.bytes)||d.bytes<0||!['extracted','error','unsupported'].includes(d.status)||!d.metadata||typeof d.metadata!=='object'||!Array.isArray(d.warnings)||d.warnings.some(x=>typeof x!=='string')||!Array.isArray(d.records)||d.records.length>LIMITS.records)fail('Invalid package document.');ids.add(d.id);if(!/^[a-f0-9]{64}$/.test(d.sha256)||!['source','template','proposal','evaluator','prompt','run-evidence','audit'].includes(d.role))fail('Invalid document hash or role.');count+=d.records.length;if(count>500000)fail('Package snapshot has too many total records.');for(const r of d.records)if(!r||typeof r.text!=='string'||typeof r.locator!=='string')fail('Invalid extracted record.');}return p;
  }
  function validateAnalysisRuns(runs){
    const str=(x)=>typeof x==='string',cit=c=>c&&['documentId','file','locator'].every(k=>str(c[k]));
    if(!Array.isArray(runs)||runs.length>1000)fail('Invalid analysis history.');for(const r of runs){if(!r||r.kind!=='deterministic-analysis-run'||!['id','packageFingerprint','completedAt','analysisType','engineVersion'].every(k=>str(r[k]))||!Number.isFinite(r.durationMs)||r.durationMs<0||!r.coverage||!['files','records','extracted','formulas'].every(k=>Number.isFinite(r.coverage[k])&&r.coverage[k]>=0)||!Array.isArray(r.findings)||r.findings.some(f=>!f||!['id','kind','severity','title','summary'].every(k=>str(f[k]))||!Array.isArray(f.citations)||f.citations.some(c=>!cit(c)))||!Array.isArray(r.facts)||r.facts.some(f=>!f||!str(f.text)||!cit(f.citation))||!Array.isArray(r.proposals)||r.proposals.some(p=>!p||!['title','reason','status'].every(k=>str(p[k])))||!Array.isArray(r.limits)||r.limits.some(x=>!str(x)))fail('Invalid analysis history.');}return runs;
  }
  const adapters=new Map();
  const adapterBoundary={status:()=>adapters.size?{connected:true,names:[...adapters.keys()]}:{connected:false,message:'No model or harness adapter is connected.'},register:adapter=>{if(!adapter||typeof adapter.name!=='string'||typeof adapter.analyze!=='function'||adapter.credentials)fail('Adapters must provide an analysis function without browser-side credentials.');adapters.set(adapter.name,adapter);},run:async(name,pkg)=>{const adapter=adapters.get(name);if(!adapter)fail('No connected analysis adapter. No model run has started.');return adapter.analyze(validatePackage(pkg));}};
  const api={ENGINE_VERSION,LIMITS,readZip,crc32,sha256,parseCsv,parseDocument,ingestFiles,inferRole,detectedFacts,analyzePackage,validatePackage,validateAnalysisRuns,citation,adapterBoundary};if(typeof module!=='undefined'&&module.exports)module.exports=api;else scope.FinancePackageEngine=api;
})(typeof window!=='undefined'?window:globalThis);
