window.FinancePlaybook={title:'The Under-60 Playbook',provenance:'User-provided task design notes, September 2026; read from the supplied 10-page PDF on 2026-10-07.',limits:'The document reports 264 submitted tasks, 226 under 0.60, and a median trajectory score of 0.519 (pages 1 and 10). These figures were not independently verified. Submitted-task selection, post-score analyses, approximate mechanism counts, and truncated text limit causal conclusions. No current-task failure probability follows from this data.',gates:[
  {id:'brief',title:'Prompt names a clear deliverable and decision',page:'7–8',question:'Does the business request preserve the context, dates, file identity, and output needed for a fair answer, while leaving genuine interpretation to the solver?'},
  {id:'teaching',title:'Prompt does not pre-solve the governing interpretation',page:'1–2, 9',question:'Compare prompt and root record. Are concrete calculation steps or the answer-bearing exception being taught? General directions to follow supplied terms may still be appropriate.'},
  {id:'operative-rule',title:'Operative rule is accessible in the supplied files',page:'2, 4, 7–8',question:'Can you point to the current authoritative excerpt and explain why the edge-case facts require interpretation, rather than a plain lookup? Never hide an expectation the solver cannot resolve.'},
  {id:'plausible-wrong',title:'Plausible wrong reading has a traceable origin',page:'2, 4',question:'If an apparently authoritative figure or stale statement is used, is its provenance and governing priority clear? A misleading figure is optional; do not introduce ambiguity merely to make a task harder.'},
  {id:'consequence',title:'The wrong reading changes a material economic decision',page:'5, 10',question:'Recompute both branches and trace the upstream error to the requested recommendation. Verify that a cap actually binds or a threshold actually crosses.'},
  {id:'one-root',title:'A propagated error is counted once',page:'5, 10; project rule',question:'Group all consequences of the same interpretation under one causal root. Several wrong downstream numbers do not create several independent failures.'},
  {id:'fingerprint',title:'Grader can locate the economic error',page:'7–10',question:'Record the wrong interpretation, right and wrong figures, units, tolerance, and exact output location. A numerical match alone does not establish a correct model.'},
  {id:'live-output',title:'Requested output and formula checks are fair and explicit',page:'2, 7–10',question:'If live formulas or a final reported recommendation are material, are they part of the disclosed deliverable? Do not invent a hidden grading requirement or reject an equivalent valid method.'},
  {id:'alternatives',title:'Acceptable alternatives are source-supported',page:'6–8, 10',question:'Replace unlimited discretion with specific defensible alternatives, justified tolerances, and equivalent methods. Resolve ambiguity rather than grading a reasonable answer as wrong.'},
  {id:'actual-run',title:'Run the current version before increasing complexity',page:'Project guidance',question:'Record an actual run ID, exact prompt/workbook/evaluator versions, observed score, and evidence. Older-version scores and playbook statistics do not establish current difficulty.'}
]};
