'use strict';
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),crypto=require('node:crypto');
const {HarnessRun}=require('./harness.cjs');const root=path.resolve(__dirname,'..');
// Private evidence modules live under private/ (ignored by git): private/evidence-module.js or any *-audit.js. The viewer runs without one; the archived one-run analysis requires it.
const privateDir=path.join(root,'private'),candidates=fs.existsSync(privateDir)?fs.readdirSync(privateDir).filter(f=>f==='evidence-module.js'||/-audit\.js$/.test(f)).sort((a,b)=>(a==='evidence-module.js'?-1:0)-(b==='evidence-module.js'?-1:0)):[];
let audit=null;if(candidates.length){global.window={};require(path.join(privateDir,candidates[0]));audit=Object.values(window).find(v=>v&&v.kind==='bundled-task-audit')||null;delete global.window;}
let state=null;const stateFile=path.join(privateDir,'model-run.js');if(fs.existsSync(stateFile)){const str=fs.readFileSync(stateFile,'utf8');try{state=JSON.parse(str.replace(/^window.FinanceModelRun\s*=\s*/,'').replace(/;\s*$/,''));}catch{}}
const runner=new HarnessRun({onChange:s=>state=s}),nonce=crypto.randomBytes(24).toString('hex'),assets=new Set(['index.html','styles.css','core.js','catalog.js','examples.js','playbook.js','research-gates.js','package-engine.js','candidate-engine.js','app.js','dashboard.js']);
const server=http.createServer(async(req,res)=>{const host=req.headers.host;if(host!==`127.0.0.1:${server.address().port}`){res.writeHead(403);return res.end('Local host required');}const url=new URL(req.url,'http://'+host);res.setHeader('Cache-Control','no-store');res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','no-referrer');
 if(url.pathname==='/api/status'&&req.method==='GET'){res.setHeader('Content-Type','application/json');return res.end(JSON.stringify({state,connection:'local-sdk-adapter',canStart:false,nonce,adapter:'deepseek-account'}));}
 if(url.pathname==='/api/cancel'&&req.method==='POST'){if(req.headers.origin!=='http://'+host||req.headers['x-finance-local']!==nonce){res.writeHead(403);return res.end('Origin authorization required');}runner.cancel();res.setHeader('Content-Type','application/json');return res.end(JSON.stringify({cancelRequested:true,state}));}
 if(req.method!=='GET'){res.writeHead(405);return res.end('Unsupported action. This release permits only the explicitly authorized one-time run.');}
 const name=url.pathname==='/'?'index.html':url.pathname.slice(1);if(!assets.has(name)){res.writeHead(404);return res.end('Not found');}let data;try{data=fs.readFileSync(path.join(root,name));}catch{res.writeHead(404);return res.end('Missing application asset');}
 if(name==='index.html')data=Buffer.from(data.toString().replace("connect-src 'none'","connect-src 'self'"));res.setHeader('Content-Type',name.endsWith('.html')?'text/html; charset=utf-8':name.endsWith('.css')?'text/css; charset=utf-8':'text/javascript; charset=utf-8');res.end(data);
});
server.listen(Number(process.env.FINANCE_STUDIO_PORT||0),'127.0.0.1',async()=>{const url=`http://127.0.0.1:${server.address().port}`;fs.writeFileSync(path.join(root,'LOCAL_SERVER.json'),JSON.stringify({url,pid:process.pid,startedAt:new Date().toISOString(),modelCallsOnLaunch:process.argv.includes('--run-approved-once')?1:0},null,2));console.log('Finance Task Studio: '+url+(audit?'':' (no private evidence module found; viewer only)'));if(process.argv.includes('--open'))require('node:child_process').spawn('open',[url],{stdio:'ignore'});if(process.argv.includes('--run-approved-once')){if(!audit){console.error('No private evidence module found; the archived analysis cannot start.');return;}try{await runner.start(audit);console.log('Harness status: '+runner.state.status);}catch(e){console.error(e.message);}}});
process.on('SIGINT',()=>{runner.cancel();server.close(()=>process.exit(0));});process.on('SIGTERM',()=>{runner.cancel();server.close(()=>process.exit(0));});
