/* Optional developer QA for the task editor. Uses an isolated headless Chromium profile; never attaches to an existing browser. */
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),{spawn}=require('node:child_process'),assert=require('node:assert/strict');
const seed=require('../examples.js');
const root=path.resolve(__dirname,'..'),out=path.join(root,process.env.QA_OUTPUT||'qa/legacy'),profile=fs.mkdtempSync(path.join(os.tmpdir(),'finance-studio-headless-'));
const binary=process.env.CHROME_BIN||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
fs.mkdirSync(out,{recursive:true});const downloads=path.join(out,'downloads');fs.rmSync(downloads,{recursive:true,force:true});fs.mkdirSync(downloads,{recursive:true});
let proc,ws,nextId=0,pending=new Map(),errors=[],network=[],resources=[],checks=[];
const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
function call(method,params={}){return new Promise((resolve,reject)=>{const id=++nextId;const timeout=setTimeout(()=>{pending.delete(id);reject(new Error('CDP timeout: '+method));},10000);pending.set(id,{resolve,reject,timeout});ws.send(JSON.stringify({id,method,params}));});}
async function evaluate(expression){const r=await call('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw new Error(r.exceptionDetails.text+' '+JSON.stringify(r.exceptionDetails.exception));return r.result.value;}
async function click(selector){await evaluate(`document.querySelector(${JSON.stringify(selector)}).click()`);await delay(50);}
async function fill(bind,value){await evaluate(`(()=>{const el=document.querySelector('[data-bind="'+${JSON.stringify(bind)}+'"]');if(!el)throw new Error('Missing field '+${JSON.stringify(bind)});el.value=${JSON.stringify(value)};el.dispatchEvent(new Event('input',{bubbles:true}));})()`);}
async function screenshot(name,width,height){await call('Emulation.setDeviceMetricsOverride',{width,height,deviceScaleFactor:1,mobile:width<700});const r=await call('Page.captureScreenshot',{format:'png',captureBeyondViewport:true});fs.writeFileSync(path.join(out,name+'.png'),Buffer.from(r.data,'base64'));const overflow=await evaluate('document.documentElement.scrollWidth>window.innerWidth');assert.equal(overflow,false,name+' horizontal overflow');checks.push(name+' fits viewport');}
async function importInput(selector,file){const {root:doc}=await call('DOM.getDocument');const {nodeId}=await call('DOM.querySelector',{nodeId:doc.nodeId,selector});await call('DOM.setFileInputFiles',{nodeId,files:[file]});await delay(200);}
const read=suffix=>{const name=fs.readdirSync(downloads).find(f=>f.endsWith(suffix));assert.ok(name,'download missing: '+suffix);return fs.readFileSync(path.join(downloads,name),'utf8');};
(async()=>{try{
  proc=spawn(binary,[...(process.getuid&&process.getuid()===0?['--no-sandbox']:[]),'--headless=new','--no-first-run','--no-default-browser-check','--disable-extensions','--disable-background-networking','--disable-component-update','--disable-default-apps','--disable-sync','--metrics-recording-only','--remote-debugging-port=0','--remote-debugging-address=127.0.0.1','--user-data-dir='+profile,'about:blank'],{stdio:['ignore','ignore','pipe']});
  const browserURL=await new Promise((resolve,reject)=>{let text='';const t=setTimeout(()=>reject(new Error('Headless browser startup timeout')),15000);proc.stderr.on('data',d=>{text+=d;const m=text.match(/DevTools listening on (ws:\/\/[^\s]+)/);if(m){clearTimeout(t);resolve(m[1]);}});proc.on('error',reject);proc.on('exit',code=>{if(code)reject(new Error('Headless browser exited '+code+' '+text.slice(-1200)));});});
  const origin=browserURL.replace(/^ws:/,'http:').split('/devtools/')[0];const targets=await(await fetch(origin+'/json/list')).json();const target=targets.find(x=>x.type==='page');
  ws=new WebSocket(target.webSocketDebuggerUrl);await new Promise((resolve,reject)=>{ws.addEventListener('open',resolve,{once:true});ws.addEventListener('error',reject,{once:true});});
  ws.addEventListener('message',e=>{const m=JSON.parse(e.data);if(m.id&&pending.has(m.id)){const p=pending.get(m.id);clearTimeout(p.timeout);pending.delete(m.id);m.error?p.reject(new Error(JSON.stringify(m.error))):p.resolve(m.result);}if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails);if(m.method==='Log.entryAdded'&&m.params.entry.level==='error')errors.push(m.params.entry);if(m.method==='Network.requestWillBeSent'){resources.push(m.params.request.url);if(/^https?:/.test(m.params.request.url))network.push(m.params.request.url);}if(m.method==='Page.javascriptDialogOpening')call('Page.handleJavaScriptDialog',{accept:true}).catch(()=>{});});
  const browserVersion=await call('Browser.getVersion');await call('Page.enable');await call('Runtime.enable');await call('Log.enable');await call('Network.enable');await call('Browser.setDownloadBehavior',{behavior:'allow',downloadPath:downloads});await call('Page.navigate',{url:'file://'+(process.env.APP_ENTRY||path.join(root,'index.html'))});await delay(300);
  assert.equal(await evaluate('document.title'),'Finance Task Studio');await click('[data-dash-action="advanced"]');assert.equal(await evaluate('document.querySelectorAll("#advanced-shell .nav-btn").length'),9);checks.push('file URL opens the task editor with all nine views without a server');
  await screenshot('desktop-workspace',1440,1000);await screenshot('mobile-blank-workspace',390,844);
  await click('[data-example="cash"]');assert.match(await evaluate('document.querySelector("#project-title").textContent'),/Atlas/);assert.equal(await evaluate('FinanceAuthoring.getProject().roots.length'),5);checks.push('synthetic worked example loads with five failure modes');
  await click('[data-tab="modes"]');assert.equal(await evaluate('document.querySelectorAll("table.shortlist tbody tr").length'),10);assert.equal(await evaluate('document.querySelectorAll("table.shortlist .pill").length'),3);assert.match(await evaluate('document.querySelector("#main").textContent'),/Five modes recorded/);checks.push('failure-mode page shows the ten-mode shortlist with three selected and the set locked');await screenshot('desktop-failure-modes',1440,1000);await screenshot('mobile-failure-modes',390,844);
  await click('[data-tab="workspace"]');await fill('p.business.prompt','word '.repeat(41));await click('[data-tab="review"]');await click('[data-action="solver-json"]');assert.match(await evaluate('document.querySelector("#toast").textContent'),/40 words/);checks.push('41-word solver export blocked in interface');
  await click('[data-tab="workspace"]');await click('[data-action="generate"]');
  await click('[data-tab="sources"]');const sourceId=await evaluate('document.querySelectorAll(".source-grid input")[0].dataset.bind.split(".")[1]');await fill('s.'+sourceId+'.reviewStatus','reviewed');await fill('s.'+sourceId+'.excerpt','PRIVATE_EVALUATOR_SECRET');assert.equal(await evaluate(`document.querySelector('[data-bind="s.${sourceId}.reviewStatus"]').value`),'pending');checks.push('source review status visibly resets after evidence edit');
  await click('[data-tab="roots"]');await fill('r.reviewStatus','reviewed');await fill('r.detectionMethod','The bridge reads 0 while funded cash is 650.');assert.equal(await evaluate(`document.querySelector('[data-bind="r.reviewStatus"]').value`),'pending');assert.equal(await evaluate('FinanceAuthoring.getProject().roots[0].detectionMethod'),'The bridge reads 0 while funded cash is 650.');checks.push('root review status visibly resets after a record-field edit');await screenshot('desktop-root',1440,1000);
  await click('[data-tab="economics"]');const outputsBefore=await evaluate('document.querySelectorAll(".output-block").length');for(const [key,value] of Object.entries({facility:'3000',fraction:'0.6',asOf:'2026-09-30',clearDate:'2026-09-30',releaseDate:'2026-10-01',opening:'100',fundedDraw:'500',otherInflows:'50',outflows:'2000'}))await fill('calc.'+key,value);await click('[data-action="calculate"]');assert.match(await evaluate('document.querySelector(".metric").textContent'),/1,350/);await click('[data-action="use-calculation"]');assert.equal(await evaluate('document.querySelectorAll(".output-block").length'),outputsBefore+1);checks.push('cash bridge calculates and is recorded as a candidate output');await screenshot('desktop-economics',1440,1000);
  await click('[data-tab="review"]');await click('[data-action="draft-guidance"]');const drafted=await evaluate('FinanceAuthoring.getProject().guidance');assert.match(drafted,/A tempting mistake/);assert.equal(await evaluate('document.querySelectorAll("#guidance-lint .finding.blocker").length'),0);checks.push('guidance drafted from the failure modes with no lint blocker');
  await fill('p.guidance','Penalize any miss of the SAF figure in cell B2:B10 — deduct points.');assert.ok(await evaluate('document.querySelectorAll("#guidance-lint .finding.blocker").length')>=3);checks.push('guidance lint flags scoring language, jargon, and dashes live');await fill('p.guidance',drafted);
  await click('[data-action="solver-json"]');await click('[data-action="evaluator-json"]');await click('[data-action="guidance-text"]');await click('[data-action="modes-text"]');await click('[data-action="working-doc"]');await click('[data-action="save"]');await delay(400);
  const solver=JSON.parse(read('solver-draft.json')),evaluator=JSON.parse(read('evaluator-draft-PRIVATE.json'));assert.ok(!JSON.stringify(solver).includes('PRIVATE_EVALUATOR_SECRET'));assert.ok(JSON.stringify(evaluator).includes('PRIVATE_EVALUATOR_SECRET'));assert.equal(evaluator.failureModeSet.historical.length,3);assert.equal(solver.suppliedFileManifest[0].file,'Treasury_Procedure.txt');assert.match(read('failure-modes-PRIVATE.txt'),/Historical Mode IDs: SYN-FM-02, SYN-FM-01, SYN-FM-05/);assert.match(read('working-document-PRIVATE.md'),/^# Derivative Task Build/);assert.ok(!/[—–]/.test(read('grader-guidance.txt')));checks.push('real downloaded exports preserve audience separation and carry the failure-mode set');
  const saved=path.join(downloads,fs.readdirSync(downloads).find(f=>f.endsWith('project.json')));await click('[data-action="new"]');await importInput('#project-file',saved);assert.match(await evaluate('document.querySelector("#project-title").textContent'),/Atlas/);assert.equal(await evaluate('FinanceAuthoring.getProject().library.modes.length'),12);checks.push('saved project imports through file picker with its library and roundtrip state');
  fs.writeFileSync(path.join(out,'invalid-project.json'),'{"schemaVersion":999}');await importInput('#project-file',path.join(out,'invalid-project.json'));assert.match(await evaluate('document.querySelector("#toast").textContent'),/Import rejected/);assert.match(await evaluate('document.querySelector("#project-title").textContent'),/Atlas/);checks.push('invalid import is rejected without replacing work');
  await click('[data-action="new"]');fs.writeFileSync(path.join(out,'library-fixture.json'),JSON.stringify(seed.library()));await click('[data-tab="modes"]');await importInput('#library-file',path.join(out,'library-fixture.json'));assert.equal(await evaluate('document.querySelectorAll("table.shortlist tbody tr").length'),10);await click('table.shortlist tbody tr button[data-action="select-mode"]');assert.equal(await evaluate('FinanceAuthoring.getProject().roots.filter(r=>r.lane==="historical").length'),1);assert.equal(await evaluate('FinanceAuthoring.getProject().roots.find(r=>r.lane==="historical").modeId'),'SYN-FM-02');checks.push('library JSON imports through the file picker; selecting a shortlist row creates a historical mode');
  await click('[data-tab="roots"]');await click('[data-action="scaffold"]');assert.match(await evaluate('FinanceAuthoring.getProject().roots.at(-1).triggeringCondition'),/hypothesis: edit before use/);checks.push('mechanism scaffold fills blank record fields as labeled hypotheses');
  await click('[data-tab="experiments"]');await evaluate(`(()=>{const f=document.querySelector('#run-form');for(const [k,v]of Object.entries({runId:'QA-ONLY-SYNTHETIC-TEST',date:'2026-10-07',model:'browser-test-fixture',score:'50',scoreMax:'100',evidence:'QA fixture — not a real model run'}))f.elements[k].value=v;f.requestSubmit();})()`);await delay(50);assert.match(await evaluate('document.querySelector("table").textContent'),/QA-ONLY/);checks.push('actual-run entry form validates and persists supplied fixture (QA only)');
  for(const id of ['workspace','modes','sources','roots','economics','review','experiments','playbook','research']){await click('[data-tab="'+id+'"]');await screenshot('mobile-'+id,390,844);}
  await click('[data-tab="research"]');await screenshot('desktop-research',1440,1000);await click('[data-tab="playbook"]');await screenshot('desktop-playbook',1440,1000);
  if(process.env.STANDALONE==='1'){assert.equal(resources.filter(url=>url.startsWith('file:')).length,1,'Standalone edition must load only its HTML file');checks.push('standalone HTML works in isolation with zero companion assets');}assert.equal(network.length,0,'The app must not issue HTTP requests');assert.equal(errors.length,0,'Browser console/runtime errors: '+JSON.stringify(errors));checks.push('zero app HTTP requests, runtime errors, and console errors');
  fs.writeFileSync(path.join(out,'browser-report.json'),JSON.stringify({passed:true,entry:process.env.APP_ENTRY||path.join(root,'index.html'),checks,resources,consoleErrors:errors,appNetworkRequests:network,browser:'Isolated headless Chromium',browserVersion,node:process.version,viewports:[{width:1440,height:1000},{width:390,height:844}],qaData:'Synthetic QA fixtures only; no real model runs performed.'},null,2));console.log(JSON.stringify({passed:true,checks},null,2));
}catch(error){console.error(error);fs.writeFileSync(path.join(out,'browser-report.json'),JSON.stringify({passed:false,checks,error:String(error),errors,network},null,2));process.exitCode=1;}finally{if(ws){try{await call('Browser.close');}catch{}ws.close();}if(proc)proc.kill();fs.rmSync(profile,{recursive:true,force:true,maxRetries:10,retryDelay:100});}})();
