/* Optional developer QA for the candidate workflow. Uses an isolated headless Chromium profile; never attaches to an existing browser. The private-module branch runs only when a locally kept evidence module exists. */
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),{spawn}=require('node:child_process'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),out=path.join(root,process.env.QA_OUTPUT||'qa/candidates'),profile=fs.mkdtempSync(path.join(os.tmpdir(),'finance-studio-headless-'));
const binary=process.env.CHROME_BIN||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
const privateDir=path.join(root,'private'),privateModule=process.env.PRIVATE_EVIDENCE==='none'?null:process.env.PRIVATE_EVIDENCE||(fs.existsSync(privateDir)?fs.readdirSync(privateDir).filter(f=>f==='evidence-module.js'||/-audit\.js$/.test(f)).sort().map(f=>path.join(privateDir,f))[0]:null);
fs.mkdirSync(out,{recursive:true});const downloads=path.join(out,'downloads');fs.rmSync(downloads,{recursive:true,force:true});fs.mkdirSync(downloads,{recursive:true});
let proc,ws,nextId=0,pending=new Map(),errors=[],network=[],resources=[],checks=[];
const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
function call(method,params={}){return new Promise((resolve,reject)=>{const id=++nextId;const timeout=setTimeout(()=>{pending.delete(id);reject(new Error('CDP timeout: '+method));},20000);pending.set(id,{resolve,reject,timeout});ws.send(JSON.stringify({id,method,params}));});}
async function evaluate(expression){const r=await call('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw new Error(r.exceptionDetails.text+' '+JSON.stringify(r.exceptionDetails.exception));return r.result.value;}
async function click(selector){await evaluate(`document.querySelector(${JSON.stringify(selector)}).click()`);await delay(50);}
async function screenshot(name,width,height){await call('Emulation.setDeviceMetricsOverride',{width,height,deviceScaleFactor:1,mobile:width<700});const r=await call('Page.captureScreenshot',{format:'png',captureBeyondViewport:true});fs.writeFileSync(path.join(out,name+'.png'),Buffer.from(r.data,'base64'));const overflow=await evaluate('document.documentElement.scrollWidth>window.innerWidth');assert.equal(overflow,false,name+' horizontal overflow');checks.push(name+' fits viewport');}
async function setFile(selector,file){const {root:doc}=await call('DOM.getDocument');const {nodeId}=await call('DOM.querySelector',{nodeId:doc.nodeId,selector});await call('DOM.setFileInputFiles',{nodeId,files:[file]});}
(async()=>{try{
  proc=spawn(binary,[...(process.getuid&&process.getuid()===0?['--no-sandbox']:[]),'--headless=new','--no-first-run','--no-default-browser-check','--disable-extensions','--disable-background-networking','--disable-component-update','--disable-default-apps','--disable-sync','--metrics-recording-only','--remote-debugging-port=0','--remote-debugging-address=127.0.0.1','--user-data-dir='+profile,'about:blank'],{stdio:['ignore','ignore','pipe']});
  const browserURL=await new Promise((resolve,reject)=>{let text='';const t=setTimeout(()=>reject(new Error('Headless browser startup timeout')),15000);proc.stderr.on('data',d=>{text+=d;const m=text.match(/DevTools listening on (ws:\/\/[^\s]+)/);if(m){clearTimeout(t);resolve(m[1]);}});proc.on('error',reject);proc.on('exit',code=>{if(code)reject(new Error('Headless browser exited '+code+' '+text.slice(-1200)));});});
  const origin=browserURL.replace(/^ws:/,'http:').split('/devtools/')[0];const targets=await(await fetch(origin+'/json/list')).json();const target=targets.find(x=>x.type==='page');
  ws=new WebSocket(target.webSocketDebuggerUrl);await new Promise((resolve,reject)=>{ws.addEventListener('open',resolve,{once:true});ws.addEventListener('error',reject,{once:true});});
  ws.addEventListener('message',e=>{const m=JSON.parse(e.data);if(m.id&&pending.has(m.id)){const p=pending.get(m.id);clearTimeout(p.timeout);pending.delete(m.id);m.error?p.reject(new Error(JSON.stringify(m.error))):p.resolve(m.result);}if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails);if(m.method==='Log.entryAdded'&&m.params.entry.level==='error')errors.push(m.params.entry);if(m.method==='Network.requestWillBeSent'){resources.push(m.params.request.url);if(/^https?:/.test(m.params.request.url))network.push(m.params.request.url);}if(m.method==='Page.javascriptDialogOpening')call('Page.handleJavaScriptDialog',{accept:true}).catch(()=>{});});
  const browserVersion=await call('Browser.getVersion');await call('Page.enable');await call('Runtime.enable');await call('Log.enable');await call('Network.enable');await call('Browser.setDownloadBehavior',{behavior:'allow',downloadPath:downloads});await call('Page.navigate',{url:'file://'+(process.env.APP_ENTRY||path.join(root,'index.html'))});await delay(300);
  assert.equal(await evaluate('FinanceDashboard.getState().candidateReview'),null);assert.equal(await evaluate('document.querySelector("#dashboard-app .model-card")===null'),true);checks.push('no candidates or provider panel before files are loaded');
  await click('[data-dash-action="example-cash"]');await delay(200);assert.equal(await evaluate('FinanceDashboard.getState().candidateReview.family'),'cash');let c=await evaluate('FinanceDashboard.getState().candidateReview.candidates[0]');assert.equal(c.outputs[0].correct,1200);assert.equal(c.outputs[0].wrong,0);assert.equal(await evaluate('document.querySelectorAll(".candidate-card").length'),3);checks.push('new cash task loads and automatically derives 1200 versus 0 bridge with no manual fields');await screenshot('desktop-new-cash-candidates',1440,1000);await screenshot('mobile-new-cash-candidates',390,844);
  await click('[data-dash-action="review-pack"]');await click('[data-dash-action="analysis-request"]');await click('[data-dash-action="candidate-solver"]');await delay(300);const review=JSON.parse(fs.readFileSync(path.join(downloads,'Candidate_Review_Pack_PRIVATE.json'))),request=JSON.parse(fs.readFileSync(path.join(downloads,'Source_Analysis_Request_PRIVATE.json')));assert.equal(review.candidates.length,3);assert.ok(request.sourceRecords.length>=3);assert.match(request.instruction,/Do not fabricate/);assert.equal(review.FailureAnalysis,undefined);const cashSolver=JSON.parse(fs.readFileSync(path.join(downloads,'cash-funded-cash-solver-DRAFT.json')));assert.ok(!JSON.stringify(cashSolver).includes('wrongInterpretation'));assert.ok(cashSolver.wordCount<=40);checks.push('private review and assistant request contain anchors; solver download stays separated and <=40 words');
  assert.equal(await evaluate('document.querySelectorAll(".candidate-rejected [data-dash-action=candidate-solver]:disabled").length'),1);checks.push('rejected same-root candidate cannot be exported as a solver draft');
  await click('[data-dash-action="candidate-edit"]');assert.equal(await evaluate('FinanceAuthoring.getProject().roots[0].outputs[0].correct'),'1200');assert.equal(await evaluate('document.querySelector("#advanced-shell").hidden'),false);checks.push('chosen candidate opens as its own populated project with calculations and source anchors');await click('[data-dash-action="close-advanced"]');
  const rootsBefore=await evaluate('FinanceAuthoring.getProject().roots.length');await click('[data-dash-action="candidate-mode"]');const added=await evaluate('(()=>{const p=FinanceAuthoring.getProject();const r=p.roots.at(-1);return {count:p.roots.length,lane:r.lane,title:r.title,outputs:r.outputs.length,anchors:r.sourceIds.length,sources:p.sources.length,hidden:document.querySelector("#advanced-shell").hidden,tab:document.querySelector("#advanced-shell .nav-btn.active").textContent};})()');assert.equal(added.count,rootsBefore+1);assert.equal(added.lane,'net-new');assert.equal(added.title,'Available credit counted as funded cash');assert.equal(added.outputs,1);assert.ok(added.anchors>0);assert.equal(added.hidden,false);assert.match(added.tab,/Root design/);checks.push('candidate added to the failure-mode set as a net-new mode with its anchors and outputs');await click('[data-dash-action="close-advanced"]');
  await click('[data-dash-tab="overview"]');await click('[data-dash-action="example-dividend"]');await delay(200);c=await evaluate('FinanceDashboard.getState().candidateReview.candidates[0]');assert.equal(c.outputs[0].correct,3680);assert.equal(c.outputs[0].wrong,4000);assert.equal(await evaluate('document.querySelectorAll(".candidate-rejected").length'),2);checks.push('new lending task calculates binding share capacity and rejects duplicate/irrelevant roots');await screenshot('mobile-new-dividend-candidates',390,844);
  await evaluate(String.raw`FinanceDashboard.ingest([new File(['Old run had errors but no verified score'],'old-run.log'),new File(['Cash budget,100000\nPrice per share,25\nShares on loan at record date,10000\nDividend per share,0.8\nProposed trade shares,3900'],'facts.csv')])`);assert.match(await evaluate('document.querySelector("#analysis-main").textContent'),/Unstructured log/);assert.equal(await evaluate('FinanceDashboard.getState().candidateReview.runEvidence[0].score'),null);checks.push('unstructured existing-task logs stay unmatched and do not create scores or root failures');
  if(privateModule){
    await setFile('#evidence-module-file',privateModule);await delay(2500);await click('[data-dash-tab="candidates"]');const expected=await evaluate('(()=>{const D=FinanceDashboard.getEvidenceModule();return {roots:D.screeningProject?D.screeningProject.roots.length:D.candidateProject.roots.length,words:FinanceCore.words(D.candidateProject.business.prompt)};})()');assert.equal(await evaluate('document.querySelectorAll(".candidate-card").length'),expected.roots);checks.push('private module candidates render from the module projects');
    await click('[data-dash-action="candidate-solver"]');await delay(400);const file=fs.readdirSync(downloads).find(f=>f.startsWith('imported-')&&f.endsWith('-solver-DRAFT.json'));assert.ok(file,'imported solver download');const solver=JSON.parse(fs.readFileSync(path.join(downloads,file)));assert.equal(solver.wordCount,expected.words);assert.ok(!JSON.stringify(solver).includes('wrongInterpretation'));assert.ok(solver.suppliedFileManifest.length>0);checks.push('imported-audit solver download preserves the exact authorized prompt without evaluator fields');
  }
  if(process.env.STANDALONE==='1'){assert.equal(resources.filter(url=>url.startsWith('file:')).length,1,'Standalone edition must load only its HTML file');checks.push('standalone HTML works in isolation with zero companion assets');}assert.equal(network.length,0,'The app must not issue HTTP requests');assert.equal(errors.length,0,'Browser console/runtime errors: '+JSON.stringify(errors));checks.push('zero app HTTP requests, runtime errors, and console errors');
  fs.writeFileSync(path.join(out,'browser-report.json'),JSON.stringify({passed:true,entry:process.env.APP_ENTRY||path.join(root,'index.html'),privateModuleExercised:!!privateModule,checks,resources,consoleErrors:errors,appNetworkRequests:network,browser:'Isolated headless Chromium',browserVersion,node:process.version,viewports:[{width:1440,height:1000},{width:390,height:844}],qaData:'Synthetic QA fixture only; no real model runs performed.'},null,2));console.log(JSON.stringify({passed:true,checks},null,2));
}catch(error){console.error(error);fs.writeFileSync(path.join(out,'browser-report.json'),JSON.stringify({passed:false,checks,error:String(error),errors,network},null,2));process.exitCode=1;}finally{if(ws){try{await call('Browser.close');}catch{}ws.close();}if(proc){const gone=proc.exitCode!==null?Promise.resolve():new Promise(r=>{proc.once('exit',r);setTimeout(r,4000);});proc.kill();await gone;}try{fs.rmSync(profile,{recursive:true,force:true,maxRetries:20,retryDelay:150});}catch{/* a leftover temporary profile is harmless and must not fail a passing suite */}}})();
