/* Optional developer QA for the package dashboard. Uses an isolated headless Chromium profile; never attaches to an existing browser. The private-module branch runs only when a locally kept evidence module exists. */
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),{spawn}=require('node:child_process'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),out=path.join(root,process.env.QA_OUTPUT||'qa/dashboard'),profile=fs.mkdtempSync(path.join(os.tmpdir(),'finance-studio-headless-'));
const binary=process.env.CHROME_BIN||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
const privateDir=path.join(root,'private'),privateModule=process.env.PRIVATE_EVIDENCE==='none'?null:process.env.PRIVATE_EVIDENCE||(fs.existsSync(privateDir)?fs.readdirSync(privateDir).filter(f=>f==='evidence-module.js'||/-audit\.js$/.test(f)).sort().map(f=>path.join(privateDir,f))[0]:null);
fs.mkdirSync(out,{recursive:true});const downloads=path.join(out,'downloads');fs.rmSync(downloads,{recursive:true,force:true});fs.mkdirSync(downloads,{recursive:true});
let proc,ws,nextId=0,pending=new Map(),errors=[],network=[],resources=[],checks=[];
const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
function call(method,params={}){return new Promise((resolve,reject)=>{const id=++nextId;const timeout=setTimeout(()=>{pending.delete(id);reject(new Error('CDP timeout: '+method));},20000);pending.set(id,{resolve,reject,timeout});ws.send(JSON.stringify({id,method,params}));});}
async function evaluate(expression){const r=await call('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw new Error(r.exceptionDetails.text+' '+JSON.stringify(r.exceptionDetails.exception));return r.result.value;}
async function click(selector){await evaluate(`document.querySelector(${JSON.stringify(selector)}).click()`);await delay(50);}
async function screenshot(name,width,height){await call('Emulation.setDeviceMetricsOverride',{width,height,deviceScaleFactor:1,mobile:width<700});const r=await call('Page.captureScreenshot',{format:'png',captureBeyondViewport:true});fs.writeFileSync(path.join(out,name+'.png'),Buffer.from(r.data,'base64'));const overflow=await evaluate('document.documentElement.scrollWidth>window.innerWidth');assert.equal(overflow,false,name+' horizontal overflow');checks.push(name+' fits viewport');}
async function setFile(selector,file){const {root:doc}=await call('DOM.getDocument');const {nodeId}=await call('DOM.querySelector',{nodeId:doc.nodeId,selector});await call('DOM.setFileInputFiles',{nodeId,files:[file]});}
(async()=>{try{
  proc=spawn(binary,[...(process.getuid&&process.getuid()===0?['--no-sandbox']:[]),'--headless=new','--no-first-run','--no-default-browser-check','--disable-extensions','--disable-background-networking','--disable-component-update','--disable-default-apps','--disable-sync','--metrics-recording-only','--remote-debugging-port=0','--remote-debugging-address=127.0.0.1','--user-data-dir='+profile,'about:blank'],{stdio:['ignore','ignore','pipe']});
  const browserURL=await new Promise((resolve,reject)=>{let text='';const t=setTimeout(()=>reject(new Error('Headless browser startup timeout')),15000);proc.stderr.on('data',d=>{text+=d;const m=text.match(/DevTools listening on (ws:\/\/[^\s]+)/);if(m){clearTimeout(t);resolve(m[1]);}});proc.on('error',reject);proc.on('exit',code=>{if(code)reject(new Error('Headless browser exited '+code+' '+text.slice(-1200)));});});
  const origin=browserURL.replace(/^ws:/,'http:').split('/devtools/')[0];const targets=await(await fetch(origin+'/json/list')).json();const target=targets.find(x=>x.type==='page');
  ws=new WebSocket(target.webSocketDebuggerUrl);await new Promise((resolve,reject)=>{ws.addEventListener('open',resolve,{once:true});ws.addEventListener('error',reject,{once:true});});
  ws.addEventListener('message',e=>{const m=JSON.parse(e.data);if(m.id&&pending.has(m.id)){const p=pending.get(m.id);clearTimeout(p.timeout);pending.delete(m.id);m.error?p.reject(new Error(JSON.stringify(m.error))):p.resolve(m.result);}if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails);if(m.method==='Log.entryAdded'&&m.params.entry.level==='error')errors.push(m.params.entry);if(m.method==='Network.requestWillBeSent'){resources.push(m.params.request.url);if(/^https?:/.test(m.params.request.url))network.push(m.params.request.url);}if(m.method==='Page.javascriptDialogOpening')call('Page.handleJavaScriptDialog',{accept:true}).catch(()=>{});});
  const browserVersion=await call('Browser.getVersion');await call('Page.enable');await call('Runtime.enable');await call('Log.enable');await call('Network.enable');await call('Browser.setDownloadBehavior',{behavior:'allow',downloadPath:downloads});await call('Page.navigate',{url:'file://'+(process.env.APP_ENTRY||path.join(root,'index.html'))});await delay(300);
  assert.equal(await evaluate('document.title'),'Finance Task Studio');
  assert.match(await evaluate('document.querySelector("#dashboard-app").textContent'),/Load a task package/);assert.equal(await evaluate('document.querySelector("#advanced-shell").hidden'),true);assert.equal(await evaluate('FinanceDashboard.getState().package.documents.length'),0);assert.equal(await evaluate('FinanceDashboard.getEvidenceModule()'),null);checks.push('public build opens with nothing loaded: no private evidence, task editor hidden');
  await screenshot('desktop-overview',1440,1000);await screenshot('mobile-overview',390,844);
  await setFile('#package-files',path.join(root,'tests','fixtures','package.zip'));await delay(600);
  const imported=await evaluate('FinanceDashboard.getState()');assert.equal(imported.audit,null);assert.equal(imported.package.documents.length,5);assert.ok(imported.package.documents.every(d=>d.status==='extracted'||d.kind==='pdf'));const wb=imported.package.documents.find(d=>d.kind==='xlsx');assert.equal(wb.records.find(r=>r.locator==='Terms!B2').value,'1800');assert.equal(wb.records.find(r=>r.locator==='Terms!B2').formula,'B1*0.6');const docx=imported.package.documents.find(d=>d.kind==='docx');assert.equal(docx.records[0].text,'Participant rule from the contract.');assert.equal(imported.candidateReview.candidates.length,3);checks.push('actual ZIP file input extracts XLSX formulas/caches, DOCX paragraphs, CSV, prompt; PDF visibly unsupported; candidates generated');
  await click('[data-dash-action="run"]');assert.equal(await evaluate('FinanceDashboard.getState().runs.length'),1);assert.match(await evaluate('document.querySelector("#local-results").textContent'),/Actual run local-/);assert.match(await evaluate('document.querySelector("#local-results").textContent'),/formulas have no saved value/);assert.match(await evaluate('document.querySelector("#local-results").textContent'),/Heuristic review cue/);checks.push('run performs deterministic checks with real ID/time/coverage and explicitly heuristic wording cues');await screenshot('desktop-results',1440,1000);
  await click('[data-dash-tab="files"]');assert.equal(await evaluate('document.querySelectorAll(".file-card").length'),5);await screenshot('desktop-files',1440,1000);await screenshot('mobile-files',390,844);
  await click('[data-dash-tab="history"]');assert.match(await evaluate('document.querySelector("#analysis-main").textContent'),/Local deterministic analysis runs/);assert.equal(await evaluate('document.querySelectorAll(".run-row").length'),1);checks.push('run history lists the local check with provenance');await screenshot('mobile-history',390,844);
  await click('[data-dash-action="export"]');await click('[data-dash-action="save-session"]');await delay(300);const saved=fs.readdirSync(downloads).find(f=>f==='Finance_Task_Analysis_PRIVATE.json');assert.ok(saved);const before=JSON.parse(fs.readFileSync(path.join(downloads,saved)));assert.equal(before.evidenceModule,undefined);
  assert.deepEqual(await evaluate(`(async()=>{await FinanceDashboard.loadSession(new File([${JSON.stringify(JSON.stringify(before))}],'session.json'));return FinanceDashboard.getState().package.fingerprint;})()`),before.package.fingerprint);checks.push('analysis workspace JSON download/import roundtrip preserves package and actual run');
  const oldFP=before.package.fingerprint;await evaluate(`FinanceDashboard.ingest([new File(['bad'],'bad.zip')])`);assert.equal(await evaluate('FinanceDashboard.getState().package.fingerprint'),oldFP);checks.push('invalid ZIP is rejected without replacing loaded evidence');
  await evaluate(`FinanceDashboard.loadSession(new File([JSON.stringify(FinanceAuthoring.getProject())],'project.json'))`);await click('[data-dash-action="advanced"]');assert.equal(await evaluate('document.querySelector("#advanced-shell").hidden'),false);checks.push('authoring project JSON opens in the task editor');await click('[data-dash-action="close-advanced"]');
  await click('[data-dash-action="failure-modes"]');assert.equal(await evaluate('document.querySelector("#advanced-shell").hidden'),false);assert.match(await evaluate('document.querySelector("#advanced-shell .nav-btn.active").textContent'),/Failure modes/);checks.push('failure-mode set opens the task editor on the failure-modes page');await click('[data-dash-action="close-advanced"]');
  if(privateModule){
    await setFile('#evidence-module-file',privateModule);await delay(2500);const st=await evaluate('(()=>{const s=FinanceDashboard.getState();return {audit:s.audit,variant:s.variant,documents:s.package.documents.length,family:s.candidateReview&&s.candidateReview.family};})()');assert.equal(st.audit,'bundled');assert.equal(st.variant,'baseline');assert.ok(st.documents>0);assert.equal(st.family,'imported-audit');const first=await evaluate('(()=>{const D=FinanceDashboard.getEvidenceModule();const o=D.candidateProject.roots[0].outputs;return {label:o[0].label,count:o.length,candidateDocs:D.candidate.documents.length};})()');checks.push('private evidence module loads locally through the file picker (never bundled)');
    await click('[data-dash-tab="results"]');assert.ok((await evaluate('document.querySelector("#analysis-main").textContent')).includes(first.label));assert.equal(await evaluate('document.querySelectorAll(".comparison-table tbody tr").length'),first.count+1);checks.push('audit views render from the module payload: outputs, headline decision, screened candidates');
    const anchors=await evaluate('document.querySelectorAll("[data-audit=\\"true\\"]").length');if(anchors){await click('[data-audit="true"]');assert.ok((await evaluate('document.querySelector("#evidence-records").textContent')).length>0);await click('[data-dash-action="close-modal"]');checks.push('module source anchors open real extracted evidence');}
    await screenshot('desktop-private-results',1440,1000);
    await click('[data-dash-action="load-candidate"]');await delay(800);const cand=await evaluate('(()=>{const s=FinanceDashboard.getState();return {variant:s.variant,documents:s.package.documents.length};})()');assert.equal(cand.variant,'candidate');assert.equal(cand.documents,first.candidateDocs);checks.push('proposed-revision package loads from the module');
    await click('[data-dash-action="export"]');await click('[data-dash-action="save-session"]');await delay(1500);const withModule=fs.statSync(path.join(downloads,'Finance_Task_Analysis_PRIVATE.json')).size;assert.ok(withModule>fs.statSync(privateModule).size*0.9);checks.push('workspace export carries the loaded module so the private analysis round-trips');
  }
  if(process.env.STANDALONE==='1'){assert.equal(resources.filter(url=>url.startsWith('file:')).length,1,'Standalone edition must load only its HTML file');checks.push('standalone HTML works in isolation with zero companion assets');}assert.equal(network.length,0,'The app must not issue HTTP requests');assert.equal(errors.length,0,'Browser console/runtime errors: '+JSON.stringify(errors));checks.push('zero app HTTP requests, runtime errors, and console errors');
  fs.writeFileSync(path.join(out,'browser-report.json'),JSON.stringify({passed:true,entry:process.env.APP_ENTRY||path.join(root,'index.html'),privateModuleExercised:!!privateModule,checks,resources,consoleErrors:errors,appNetworkRequests:network,browser:'Isolated headless Chromium',browserVersion,node:process.version,viewports:[{width:1440,height:1000},{width:390,height:844}],qaData:'Synthetic QA fixture only; no real model runs performed.'},null,2));console.log(JSON.stringify({passed:true,checks},null,2));
}catch(error){console.error(error);fs.writeFileSync(path.join(out,'browser-report.json'),JSON.stringify({passed:false,checks,error:String(error),errors,network},null,2));process.exitCode=1;}finally{if(ws){try{await call('Browser.close');}catch{}ws.close();}if(proc)proc.kill();fs.rmSync(profile,{recursive:true,force:true,maxRetries:10,retryDelay:100});}})();
