/* HISTORICAL verification of the adapter UI before DeepSeek work was cancelled. The delivered default UI intentionally hides this panel and no longer polls the provider. Do not use this as a current offline acceptance test. */
/* Optional developer QA. Uses an isolated headless Chromium profile; never attaches to an existing browser. */
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),{spawn}=require('node:child_process'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),out=path.join(root,process.env.QA_OUTPUT||'qa'),profile=fs.mkdtempSync(path.join(os.tmpdir(),'finance-studio-headless-'));
const binary=process.env.CHROME_BIN||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
fs.mkdirSync(out,{recursive:true});const downloads=path.join(out,'downloads');fs.rmSync(downloads,{recursive:true,force:true});fs.mkdirSync(downloads,{recursive:true});
let proc,ws,nextId=0,pending=new Map(),errors=[],network=[],resources=[],checks=[];
const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
function call(method,params={}){return new Promise((resolve,reject)=>{const id=++nextId;const timeout=setTimeout(()=>{pending.delete(id);reject(new Error('CDP timeout: '+method));},10000);pending.set(id,{resolve,reject,timeout});ws.send(JSON.stringify({id,method,params}));});}
async function evaluate(expression){const r=await call('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw new Error(r.exceptionDetails.text+' '+JSON.stringify(r.exceptionDetails.exception));return r.result.value;}
async function click(selector){await evaluate(`document.querySelector(${JSON.stringify(selector)}).click()`);await delay(50);}
async function fill(bind,value){await evaluate(`(()=>{const el=document.querySelector('[data-bind="'+${JSON.stringify(bind)}+'"]');if(!el)throw new Error('Missing field '+${JSON.stringify(bind)});el.value=${JSON.stringify(value)};el.dispatchEvent(new Event('input',{bubbles:true}));})()`);}
async function screenshot(name,width,height){await call('Emulation.setDeviceMetricsOverride',{width,height,deviceScaleFactor:1,mobile:width<700});const r=await call('Page.captureScreenshot',{format:'png',captureBeyondViewport:true});fs.writeFileSync(path.join(out,name+'.png'),Buffer.from(r.data,'base64'));const overflow=await evaluate('document.documentElement.scrollWidth>window.innerWidth');assert.equal(overflow,false,name+' horizontal overflow');checks.push(name+' fits viewport');}
async function importFile(file){const {root:doc}=await call('DOM.getDocument');const {nodeId}=await call('DOM.querySelector',{nodeId:doc.nodeId,selector:'#project-file'});await call('DOM.setFileInputFiles',{nodeId,files:[file]});await delay(150);}
(async()=>{try{
  proc=spawn(binary,['--headless=new','--no-first-run','--no-default-browser-check','--disable-extensions','--disable-background-networking','--disable-component-update','--disable-default-apps','--disable-sync','--metrics-recording-only','--remote-debugging-port=0','--remote-debugging-address=127.0.0.1','--user-data-dir='+profile,'about:blank'],{stdio:['ignore','ignore','pipe']});
  const browserURL=await new Promise((resolve,reject)=>{let text='';const t=setTimeout(()=>reject(new Error('Headless browser startup timeout')),15000);proc.stderr.on('data',d=>{text+=d;const m=text.match(/DevTools listening on (ws:\/\/[^\s]+)/);if(m){clearTimeout(t);resolve(m[1]);}});proc.on('error',reject);proc.on('exit',code=>{if(code)reject(new Error('Headless browser exited '+code+' '+text.slice(-1200)));});});
  const origin=browserURL.replace(/^ws:/,'http:').split('/devtools/')[0];const targets=await(await fetch(origin+'/json/list')).json();const target=targets.find(x=>x.type==='page');
  ws=new WebSocket(target.webSocketDebuggerUrl);await new Promise((resolve,reject)=>{ws.addEventListener('open',resolve,{once:true});ws.addEventListener('error',reject,{once:true});});
  ws.addEventListener('message',e=>{const m=JSON.parse(e.data);if(m.id&&pending.has(m.id)){const p=pending.get(m.id);clearTimeout(p.timeout);pending.delete(m.id);m.error?p.reject(new Error(JSON.stringify(m.error))):p.resolve(m.result);}if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails);if(m.method==='Log.entryAdded'&&m.params.entry.level==='error')errors.push(m.params.entry);if(m.method==='Network.requestWillBeSent'){resources.push(m.params.request.url);if(/^https?:/.test(m.params.request.url))network.push(m.params.request.url);}if(m.method==='Page.javascriptDialogOpening')call('Page.handleJavaScriptDialog',{accept:true}).catch(()=>{});});
  const browserVersion=await call('Browser.getVersion');await call('Page.enable');await call('Runtime.enable');await call('Log.enable');await call('Network.enable');await call('Browser.setDownloadBehavior',{behavior:'allow',downloadPath:downloads});await call('Page.navigate',{url:process.env.APP_ENTRY||'http://127.0.0.1:61986'});await delay(300);


  await delay(2700);assert.match(await evaluate('document.querySelector(".model-card").textContent'),/Connected local Harness/);assert.match(await evaluate('document.querySelector(".model-card").textContent'),/12,000-token output limit/);checks.push('Connected UI displays actual incomplete run with its real output-limit reason');
  await click('[data-dash-action="model-events"]');assert.match(await evaluate('document.querySelector(".evidence-dialog").textContent'),/d1992888-0680-4bd8-acbf-aca3804d8cb9/);assert.match(await evaluate('document.querySelector(".evidence-dialog").textContent'),/62188/);checks.push('Run details show actual session ID, usage, timestamps and durable event receipt');await click('[data-dash-action="close-modal"]');
  assert.equal(await evaluate(`(async()=>{const r=await fetch('/api/cancel',{method:'POST'});return r.status;})()`),403);checks.push('Mutation rejected without same-origin anti-CSRF token');
  assert.equal(await evaluate(`(async()=>{const r=await fetch('/api/run',{method:'POST'});return r.status;})()`),405);checks.push('No exposed endpoint can silently re-use consumed one-run approval');
  await screenshot('desktop-connected-model-status',1440,1000);await screenshot('mobile-connected-model-status',390,844);
  assert.equal(errors.filter(e=>!String(e.text||'').includes('Failed to load resource')).length,0,'Unexpected browser errors');
  fs.writeFileSync(path.join(out,'browser-report.json'),JSON.stringify({passed:true,checks,consoleErrors:errors,networkRequests:network,note:'Read-only existing-run verification; no inference triggered by this test'},null,2));console.log(JSON.stringify({passed:true,checks},null,2));
}catch(error){console.error(error);fs.writeFileSync(path.join(out,'browser-report.json'),JSON.stringify({passed:false,checks,error:String(error),errors,network},null,2));process.exitCode=1;}finally{if(ws){try{await call('Browser.close');}catch{}ws.close();}if(proc)proc.kill();fs.rmSync(profile,{recursive:true,force:true,maxRetries:10,retryDelay:100});}})();
