const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');const E=require('../package-engine.js');
const bytes=s=>new TextEncoder().encode(s);
const doc=(extra={})=>({id:'one',name:'Task_Prompt.txt',bytes:20,sha256:'a'.repeat(64),role:'prompt',status:'extracted',kind:'txt',records:[{locator:'Line 1',text:'Update the workbook and recommend the trade.'}],metadata:{},warnings:[],...extra});
const pkg=(documents=[doc()])=>({kind:'finance-task-package',schemaVersion:1,id:'p1',title:'QA fixture',fingerprint:'a'.repeat(64),documents});
test('ZIP checksum validation and supported office containers are indexed',async()=>{const z=await E.readZip(fs.readFileSync(__dirname+'/fixtures/package.zip'));assert.equal(z.entries.size,5);assert.match(await z.text('Task_Prompt.txt'),/fixed point/);const b=await z.get('terms.xlsx');const wb=await E.readZip(b);assert.ok(wb.entries.has('xl/workbook.xml'));});
test('invalid ZIP, encrypted flag, unsafe paths, CRC corruption rejected',async()=>{await assert.rejects(E.readZip(bytes('bad')),/Invalid ZIP/);const original=fs.readFileSync(__dirname+'/fixtures/package.zip');let encrypted=Buffer.from(original);let at=encrypted.indexOf(Buffer.from([0x50,0x4b,0x01,0x02]));encrypted.writeUInt16LE(1,at+8);await assert.rejects(E.readZip(encrypted),/Encrypted/);let unsafe=Buffer.from(original);unsafe.write('../badxxxx',at+46);await assert.rejects(E.readZip(unsafe),/unsafe path/);let corrupt=Buffer.from(original);corrupt.writeUInt32LE(1,at+16);const z=await E.readZip(corrupt);await assert.rejects(z.get('terms.xlsx'),/checksum/);});
test('CSV quotes, embedded newline, invalid quotes',()=>{assert.deepEqual(E.parseCsv('a,"b,c"\r\n"x\ny","quote ""yes"""'),[['a','b,c'],['x\ny','quote "yes"']]);assert.throws(()=>E.parseCsv('"unfinished'),/unclosed/);});
test('file ingestion handles text/PDF without pretending PDF extracted',async()=>{const p=await E.ingestFiles([new File(['hello'],'note.txt'),new File(['%PDF'],'note.pdf')]);assert.equal(p.documents[0].records[0].text,'hello');assert.equal(p.documents[1].status,'unsupported');assert.equal(p.fingerprint.length,64);});
test('invalid package rejects duplicate IDs, hashes, roles and record types',()=>{assert.throws(()=>E.validatePackage(pkg([doc(),doc()])));assert.throws(()=>E.validatePackage(pkg([doc({sha256:'x'})])));assert.throws(()=>E.validatePackage(pkg([doc({role:'secret'})])));assert.throws(()=>E.validatePackage(pkg([doc({records:[{text:4,locator:'x'}]})])));});
test('project roundtrip and deterministic findings have no invented scores',()=>{const p=JSON.parse(JSON.stringify(pkg()));E.validatePackage(p);const r=E.analyzePackage(p,{runId:'actual-test-call',now:'2026-10-07T00:00:00Z'});assert.equal(r.id,'actual-test-call');assert.equal(r.findings.length,0);assert.equal(r.score,undefined);assert.equal(r.failureProbability,undefined);assert.match(r.limits[0],/No model/);});
test('saved errors, missing caches and unsupported files produce evidence-limited findings',()=>{const r=E.analyzePackage(pkg([doc(),doc({id:'two',name:'source.xlsx',role:'source',kind:'xlsx',records:[{locator:'S!A1',text:'#REF!',type:'e'},{locator:'S!A2',text:'=1+1',hasFormula:true,cachePresent:false}],metadata:{formulas:1,externalLinks:1}})]));assert.ok(r.findings.some(x=>x.title.includes('saved formula error')&&x.citations[0].locator==='S!A1'));assert.ok(r.findings.some(x=>x.title.includes('no saved value')));assert.ok(r.findings.every(f=>f.kind!=='semantic'));});
test('teaching language is only heuristic, historical differences are not generic contradictions',()=>{const r=E.analyzePackage(pkg([doc({records:[{locator:'Line 1',text:'Use the formula to solve the fixed point.'}]}),doc({id:'a',name:'terms_v6.txt',role:'source'}),doc({id:'b',name:'terms_v8.txt',role:'source'})]));assert.ok(r.findings.find(f=>f.title.includes('answer-bearing')).kind==='heuristic');assert.match(r.findings.find(f=>f.title.includes('version')).summary,/Historical/);});
test('private evaluator records do not enter detected source facts',()=>{const p=pkg([doc({role:'evaluator',records:[{locator:'A1',text:'SECRET: 5.55 price'}]})]);assert.equal(E.detectedFacts(p).length,0);});
test('unconnected adapter cannot imply a model run',async()=>{assert.equal(E.adapterBoundary.status().connected,false);await assert.rejects(E.adapterBoundary.run('none',pkg()),/No model run/);});

test('malformed run histories cannot crash imported dashboard views',()=>{const r=E.analyzePackage(pkg());assert.equal(E.validateAnalysisRuns([r]).length,1);for(const field of ['limits','facts','proposals','findings']){const bad=structuredClone(r);bad[field]=null;assert.throws(()=>E.validateAnalysisRuns([bad]),/Invalid analysis history/);}});
